import {t,type Lang} from '@/lib/i18n';
import {RELATIONSHIP_KINDS,RELATIONSHIP_STATUSES,RELATIONSHIP_OPPORTUNITY_STATUSES} from '@/lib/sales-relationship-policy';
export const relationshipLabels:Record<string,[string,string]>={AGENT:['Agent','代理'],PARTNER:['Partner','合作伙伴'],SCHOOL:['School','学校'],PARENT:['Parent','家长'],CONTACT:['Contact','其他联系人'],ACTIVE:['Active','维护中'],NURTURING:['Developing','培育中'],DORMANT:['Dormant','暂缓'],ARCHIVED:['Archived','已归档'],OPEN:['Open','待推进'],IN_PROGRESS:['In progress','进行中'],WON:['Agreed / won','已达成'],LOST:['Closed / lost','未达成'],PAUSED:['Paused','已暂停']};
export function relationLabel(lang:Lang,key:string){const pair=relationshipLabels[key];return pair?t(lang,...pair):key;}
export const panel={border:'1px solid #dbe3ec',borderRadius:12,padding:16,background:'#fff'};
export const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12};
export function dateInput(value:Date|null|undefined){return value?new Date(value.getTime()+8*3600000).toISOString().slice(0,16):'';}
export function Field({lang,name,en,zh,value='',type='text',required=false}:{lang:Lang;name:string;en:string;zh:string;value?:string;type?:string;required?:boolean}){return <label style={{display:'grid',gap:5}}>{t(lang,en,zh)}<input name={name} defaultValue={value} type={type} required={required} style={{padding:8,border:'1px solid #cbd5e1',borderRadius:6,minWidth:0}}/></label>;}
export function Area({lang,name,en,zh,value='',required=false}:{lang:Lang;name:string;en:string;zh:string;value?:string;required?:boolean}){return <label style={{display:'grid',gap:5}}>{t(lang,en,zh)}<textarea name={name} defaultValue={value} required={required} rows={3} style={{padding:8,border:'1px solid #cbd5e1',borderRadius:6}}/></label>;}
export function Options({lang,name,values,value,en,zh}:{lang:Lang;name:string;values:readonly string[];value:string;en:string;zh:string}){return <label style={{display:'grid',gap:5}}>{t(lang,en,zh)}<select name={name} defaultValue={value} style={{padding:8,border:'1px solid #cbd5e1',borderRadius:6}}>{values.map(v=><option key={v} value={v}>{relationLabel(lang,v)}</option>)}</select></label>;}
type Profile={name?:string;kind?:string;status?:string;ownerName?:string|null;contactName?:string|null;contactEmail?:string|null;contactPhone?:string|null;contactWechat?:string|null;nextAction?:string|null;nextActionDue?:Date|null;note?:string|null};
export function ProfileFields({lang,row={}}:{lang:Lang;row?:Profile}){return <><div style={grid}><Field lang={lang} name="name" en="Relationship name" zh="关系名称" value={row.name} required/><Options lang={lang} name="kind" en="Type" zh="类型" values={RELATIONSHIP_KINDS} value={row.kind??'CONTACT'}/><Options lang={lang} name="status" en="Relationship status" zh="关系状态" values={RELATIONSHIP_STATUSES} value={row.status??'ACTIVE'}/><Field lang={lang} name="ownerName" en="Relationship owner" zh="关系负责人" value={row.ownerName??''}/><Field lang={lang} name="contactName" en="Contact person" zh="联系人" value={row.contactName??''}/><Field lang={lang} name="contactEmail" en="Email" zh="邮箱" value={row.contactEmail??''}/><Field lang={lang} name="contactPhone" en="Phone" zh="电话" value={row.contactPhone??''}/><Field lang={lang} name="contactWechat" en="WeChat" zh="微信" value={row.contactWechat??''}/><Field lang={lang} name="nextAction" en="Next action" zh="下一步" value={row.nextAction??''}/><Field lang={lang} name="nextActionDue" en="Next follow-up (Singapore)" zh="下次跟进（新加坡时间）" type="datetime-local" value={dateInput(row.nextActionDue)}/></div><Area lang={lang} name="note" en="Relationship notes" zh="关系备注" value={row.note??''}/></>;}
export function OpportunityFields({lang,row}:{lang:Lang;row?:{title:string;status:string;ownerName:string|null;nextAction:string|null;nextActionDue:Date|null;estimatedAmount:{toString():string}|null;note:string|null}}){return <><div style={grid}><Field lang={lang} name="title" en="Project or activity" zh="合作项目或活动" value={row?.title} required/><Options lang={lang} name="status" en="Project status" zh="项目状态" values={RELATIONSHIP_OPPORTUNITY_STATUSES} value={row?.status??'OPEN'}/><Field lang={lang} name="ownerName" en="Project owner" zh="项目负责人" value={row?.ownerName??''}/><Field lang={lang} name="estimatedAmount" en="Potential value (SGD; estimate only)" zh="潜在金额（SGD，仅估计）" value={row?.estimatedAmount?.toString()??''}/><Field lang={lang} name="nextAction" en="Next action" zh="下一步" value={row?.nextAction??''}/><Field lang={lang} name="nextActionDue" en="Next follow-up (Singapore)" zh="下次跟进（新加坡时间）" type="datetime-local" value={dateInput(row?.nextActionDue)}/></div><Area lang={lang} name="note" en="Notes" zh="备注" value={row?.note??''}/></>;}
