import RelationshipForm from './RelationshipForm';
import {requireResourceUser} from '@/lib/auth';
import {prisma} from '@/lib/prisma';
import {getLang,t} from '@/lib/i18n';
import {formatBusinessDateTime} from '@/lib/date-only';
import {createRelationshipAction} from './actions';
import {panel,grid,ProfileFields,relationLabel} from './fields';
export default async function RelationshipsPage({searchParams}:{searchParams?:Promise<{q?:string;status?:string;focus?:string;err?:string;ok?:string}>}){
 const user=await requireResourceUser(),lang=await getLang(),sp=await searchParams,now=new Date();
 const q=String(sp?.q??'').trim(),archived=sp?.status==='ARCHIVED',due=sp?.focus==='due';
 const [rows,pending]=await Promise.all([prisma.salesRelationship.findMany({where:{status:archived?'ARCHIVED':{not:'ARCHIVED'},...(q?{OR:[{name:{contains:q,mode:'insensitive'}},{ownerName:{contains:q,mode:'insensitive'}},{contactName:{contains:q,mode:'insensitive'}}]}:{}),...(due?{nextActionDue:{lte:now}}:{})},include:{_count:{select:{leads:true,opportunities:true}}},orderBy:[{nextActionDue:'asc'},{updatedAt:'desc'}],take:201}),prisma.lead.count({where:{recordKind:'UNREVIEWED',isArchived:false}})]);
 return <main style={{display:'grid',gap:16}}><header><h1>{t(lang,'Relationships & referrals','关系与转介')}</h1><p>{t(lang,'Maintain each relationship and follow its students and cooperation projects separately.','持续维护每段关系，分别跟进其介绍的学生和合作项目。')}</p><a href="/admin/leads">{t(lang,'Student opportunities & original records','学生商机与原始记录')}</a></header>
 {sp?.err?<p role="alert" style={{color:'#991b1b'}}>{sp.err}</p>:null}{sp?.ok?<p role="status">{t(lang,'Saved','已保存')}</p>:null}
 <section style={panel}><form method="get" style={{display:'flex',gap:10,flexWrap:'wrap'}}><input name="q" defaultValue={q} aria-label={t(lang,'Search relationship or owner','搜索关系或负责人')} placeholder={t(lang,'Search relationship or owner','搜索关系或负责人')}/><select name="status" defaultValue={archived?'ARCHIVED':''} aria-label={t(lang,'Scope','范围')}><option value="">{t(lang,'Current relationships','当前关系')}</option><option value="ARCHIVED">{t(lang,'Archived relationships','已归档关系')}</option></select><select name="focus" defaultValue={due?'due':''} aria-label={t(lang,'Follow-up filter','跟进筛选')}><option value="">{t(lang,'All follow-ups','全部跟进')}</option><option value="due">{t(lang,'Due for follow-up','已到跟进时间')}</option></select><button>{t(lang,'Apply','应用')}</button></form></section>
 {pending?<aside style={panel}><a href="/admin/leads?recordKind=UNREVIEWED">{t(lang,`${pending} original records need classification`,`${pending} 条原始记录待分类核对`)}</a><p>{t(lang,'Names alone do not establish a relationship or a student identity. Original records remain available until reviewed.','仅凭名称无法确定关系和学生身份。核对前保留原记录。')}</p></aside>:null}
 <details style={panel}><summary style={{fontWeight:700,cursor:'pointer'}}>{t(lang,'Create relationship','新建关系档案')}</summary><RelationshipForm lang={lang} action={createRelationshipAction} style={{display:'grid',gap:12,marginTop:16}}><ProfileFields lang={lang} row={{ownerName:user.name}}/><button>{t(lang,'Create relationship','创建关系档案')}</button></RelationshipForm></details>
 <section style={grid}>{rows.slice(0,200).map(row=><article key={row.id} style={panel}><div>{relationLabel(lang,row.kind)} · {relationLabel(lang,row.status)}</div><h2><a href={`/admin/relationships/${row.id}`}>{row.name}</a></h2><p>{t(lang,'Owner','负责人')}: {row.ownerName||t(lang,'Unassigned','未分配')}</p><p>{row.nextAction||t(lang,'Set a next action','请设置下一步')}</p><p style={{color:row.nextActionDue&&row.nextActionDue<=now?'#b45309':undefined}}>{t(lang,'Next follow-up','下次跟进')}: {row.nextActionDue?formatBusinessDateTime(row.nextActionDue):t(lang,'Not set','未设置')}</p><small>{t(lang,'Linked records','关联记录')}: {row._count.leads} · {t(lang,'Cooperation projects','合作项目')}: {row._count.opportunities}</small></article>)}</section>
 {!rows.length?<p>{t(lang,'No relationships match these filters. Create a profile to start maintaining a relationship.','当前筛选没有关系档案。可新建档案开始维护。')}</p>:null}{rows.length>200?<p>{t(lang,'Showing the first 200 results. Narrow the search to find more.','当前展示前200条，请缩小筛选范围查找更多记录。')}</p>:null}</main>;
}
