import {t,type Lang} from '@/lib/i18n';
import type {RelationshipActor} from '@/lib/sales-relationship-policy';
import {canReadSalesEvidence} from '@/lib/sales-evidence-policy';
import {readSalesContractEvidence,listSalesContractCandidates} from '@/lib/sales-evidence';
import {formatBusinessDateTime} from '@/lib/date-only';
import RelationshipForm from './RelationshipForm';
import {saveSalesEvidenceAction} from './actions';
import {panel} from './fields';
export default async function SalesContractEvidencePanel({actor,lang,scope,lead}:{actor:RelationshipActor;lang:Lang;scope:{leadId:string}|{relationshipId:string};lead?:{id:string;updatedAt:Date;convertedStudentId:string|null;relationshipId:string|null;recordKind:string;isArchived:boolean}}){
 if(!canReadSalesEvidence(actor))return <details style={panel}><summary>{t(lang,'Contract attribution','合同归属')}</summary><p>{t(lang,'An authorized administrator can review contract evidence. Your existing finance permissions remain unchanged.','具备权限的管理员可核对合同凭据，沿用现有财务权限。')}</p></details>;
 const {rows,summary}=await readSalesContractEvidence(actor,scope);
 const canAttach=lead&&!actor.isObserver&&lead.convertedStudentId&&lead.relationshipId&&lead.recordKind==='STUDENT'&&!lead.isArchived;
 const candidates=canAttach?await listSalesContractCandidates(actor,lead.id):[];
 return <details style={panel}><summary>{t(lang,'Reviewed contract attribution','已核对合同归属')} · {summary.assigned?t(lang,`${summary.signedContracts} signed · ${summary.pending} pending · ${summary.review} need review`,`${summary.signedContracts}份已签署 · ${summary.pending}份待签署 · ${summary.review}份待核对`):t(lang,'No active attribution','暂无有效归属')}</summary>
 <p>{t(lang,'Only explicitly reviewed contracts count here. A student record, Won deal or signed contract does not confirm payment. Reviewed parent receipts are shown separately below.','这里只统计已明确核对归属的合同。学生建档、商机成交或合同签署均不代表已收款，已核对直客收据在下方单独展示。')}</p>
 {rows.map(row=><article key={row.id} style={{borderTop:'1px solid #e2e8f0',padding:'12px 0',overflowWrap:'anywhere'}}><p><a href={`/admin/leads/${row.leadId}`}>{row.lead.studentName} · {row.lead.leadNo}</a> · {t(lang,row.en,row.zh)}</p><p>{t(lang,'Contract ID','合同编号')}: {row.documentId}</p>{row.source?<p><a href={`/admin/packages/${row.source.packageId}/contract`}>{t(lang,'Open contract history','打开合同历史')}</a> · {t(lang,'Created','创建时间')}: {formatBusinessDateTime(row.source.createdAt)}{row.source.signedAt?` · ${t(lang,'Signed','签署时间')}: ${formatBusinessDateTime(row.source.signedAt)}`:''}</p>:null}<p>{t(lang,'Review basis','核对依据')}: {row.reviewNote}</p><small>{row.reviewedBy} · {formatBusinessDateTime(row.updatedAt)}</small>
 {lead&&row.status==='ACTIVE'&&!actor.isObserver?<details><summary>{t(lang,'Revoke this attribution','撤销此归属')}</summary><RelationshipForm lang={lang} action={saveSalesEvidenceAction} style={{display:'grid',gap:8}}><input type="hidden" name="action" value="REVOKE"/><input type="hidden" name="leadId" value={lead.id}/><input type="hidden" name="assignmentId" value={row.id}/><input type="hidden" name="expectedUpdatedAt" value={row.updatedAt.toISOString()}/><label>{t(lang,'Reason (contract itself is unchanged)','原因（不会更改合同本身）')}<textarea name="reviewNote" required maxLength={2000}/></label><button>{t(lang,'Revoke attribution only','仅撤销归属')}</button></RelationshipForm></details>:null}</article>)}
 {canAttach?<details style={{marginTop:12}}><summary>{t(lang,'Review and attribute a contract','核对并归属合同')}</summary><p>{t(lang,'Latest 100 contracts for the exact linked student. Review the original contract before selecting. Uncertain referral ownership stays unassigned.','显示准确关联学生最近100份合同。请核对原合同后选择，转介归属不确定时保持未归属。')}</p><RelationshipForm lang={lang} action={saveSalesEvidenceAction} style={{display:'grid',gap:12}}><input type="hidden" name="action" value="ATTACH"/><input type="hidden" name="leadId" value={lead.id}/><input type="hidden" name="expectedUpdatedAt" value={lead.updatedAt.toISOString()}/><label style={{display:'grid'}}>{t(lang,'Exact contract','准确合同')}<select name="contract" required defaultValue="" style={{maxWidth:'100%'}}><option value="">{t(lang,'Select after reviewing the contract','核对合同后选择')}</option>{candidates.map(c=><option key={c.id} value={`${c.id}|${c.updatedAt.toISOString()}`} disabled={c.assignedElsewhere||['REVIEW','INACTIVE'].includes(c.state)}>{formatBusinessDateTime(c.createdAt)} · {c.id} · {c.assignedElsewhere?t(lang,'Attributed to another lead','已归属其他商机'):t(lang,c.en,c.zh)}</option>)}</select></label><label style={{display:'grid'}}>{t(lang,'Evidence that this relationship generated this contract','此合同来自该关系转介的核对依据')}<textarea name="reviewNote" maxLength={2000} required/></label><button disabled={!candidates.some(c=>!c.assignedElsewhere&&!['REVIEW','INACTIVE'].includes(c.state))}>{t(lang,'Save reviewed attribution','保存已核对归属')}</button></RelationshipForm></details>:lead?<p>{t(lang,'Link an active student opportunity to an exact student and relationship before attributing contracts. Observers can view only.','归属合同前，请将有效学生商机关联到准确的学生及关系档案。观察员仅可查看。')}</p>:null}
 </details>;
}
