import {t,type Lang} from '@/lib/i18n';
import type {RelationshipActor} from '@/lib/sales-relationship-policy';
import {canReadSalesEvidence} from '@/lib/sales-evidence-policy';
import {readParentInvoiceEvidence,listParentInvoiceCandidates} from '@/lib/sales-invoice-evidence';
import {readPartnerInvoiceEvidence,listPartnerInvoiceCandidates} from '@/lib/sales-partner-invoice-evidence';
import {formatBusinessDateTime} from '@/lib/date-only';
import RelationshipForm from './RelationshipForm';
import {saveParentInvoiceEvidenceAction,savePartnerInvoiceEvidenceAction,saveSalesEvidenceAction} from './actions';
import {panel,grid} from './fields';
const money=(cents:number)=>`SGD ${(cents/100).toFixed(2)}`;
export default async function SalesInvoiceEvidencePanel({actor,lang,scope,lead,channel='PARENT'}:{actor:RelationshipActor;lang:Lang;channel?:'PARENT'|'PARTNER';scope:{leadId:string}|{relationshipId:string};lead?:{id:string;updatedAt:Date;convertedStudentId:string|null;relationshipId:string|null;recordKind:string;isArchived:boolean}}){
 if(!canReadSalesEvidence(actor))return null;
 const partner=channel==='PARTNER';
 const evidence=partner?await readPartnerInvoiceEvidence(actor,scope):await readParentInvoiceEvidence(actor,scope).then(value=>({...value,unassignedInvoices:null,summary:{...value.summary,creditCents:0,adjustedInvoiceCents:0},rows:value.rows.map(row=>({...row,partnerId:null,mode:null,creditCents:null,adjustedInvoiceCents:null}))}));
 const {rows,summary}=evidence;
 const canAttach=lead&&!actor.isObserver&&lead.convertedStudentId&&lead.relationshipId&&lead.recordKind==='STUDENT'&&!lead.isArchived;
 const candidates=canAttach?await (partner?listPartnerInvoiceCandidates:listParentInvoiceCandidates)(actor,lead.id):{valid:true,rows:[]};
 return <details style={panel}><summary>{partner?t(lang,'Reviewed partner invoices & receipts','已核对合作方发票与收据'):t(lang,'Reviewed parent invoices & receipts','已核对直客发票与收据')} · {summary.verifiedInvoices?t(lang,`${summary.verifiedInvoices} verified invoices`,`${summary.verifiedInvoices}张已核实发票`):t(lang,'No verified invoice attribution','尚无已核实发票归属')}{summary.review?` · ${t(lang,`${summary.review} need review`,`${summary.review}项待核对`)}`:''}</summary>
 <p>{partner?t(lang,'Only explicitly reviewed invoices covering this exact student are included. Mixed-student, manual or unbound historical invoices need allocation review; amounts are never divided automatically. Approved receipts are the amounts recorded and approved by Finance. Credits reduce the invoice total, not the receipt amount again, and do not prove a cash refund.','仅计入已明确核对、且全部属于该学生的发票。多学生、手工或缺少关联的历史发票待核对，不自动分摊。已批准收据按财务实际记录及审批统计；贷项减少发票金额，不重复抵减收据金额，也不代表已现金退款。'):t(lang,'Totals cover explicitly attributed parent invoices only. Approved receipt amounts follow current finance approvals; they are not net revenue after refunds. Partner invoices and unassigned business are excluded.','合计仅涵盖已明确归属的直客发票。已批准收据金额依照当前财务审批，不等于扣除退款后的净收入。合作方发票及未归属业务未计入。')}</p>
 {partner?<p><a href="/admin/finance/documents?channel=PARTNER&type=INVOICE">{t(lang,'Company-wide partner invoices without active attribution','全公司尚无有效归属的合作方发票')}: {evidence.unassignedInvoices??t(lang,'Needs review','待核对')}</a> · {t(lang,'This is not a count for this relationship.','此数量不代表当前关系名下业务。')}</p>:null}
 {summary.verifiedInvoices?<div style={grid}>{[[t(lang,'Verified invoice amount','已核实发票金额'),money(summary.invoiceCents)],...(partner?[[t(lang,'Issued credit amount','已开贷项金额'),money(summary.creditCents)],[t(lang,'Adjusted invoice amount','调整后发票金额'),money(summary.adjustedInvoiceCents)]]:[]),[t(lang,'Approved receipt amount','已批准收据金额'),money(summary.approvedCents)],[t(lang,'Pending / rejected receipts','待审批／已驳回收据'),`${summary.pendingReceipts} / ${summary.rejectedReceipts}`]].map(([label,value])=><div key={label}><strong>{label}</strong><p>{value}</p></div>)}</div>:<p>{t(lang,'No verified total yet; this does not mean no business or no payments.','尚无已核实合计，并不代表没有业务或没有收款。')}</p>}
 {rows.map(row=><article key={row.id} style={{borderTop:'1px solid #e2e8f0',padding:'12px 0',overflowWrap:'anywhere'}}><p><strong>{row.invoiceNo}</strong> · {t(lang,row.en,row.zh)}</p><p><a href={`/admin/leads/${row.leadId}`}>{row.lead.studentName} · {row.lead.leadNo}</a></p><p>{t(lang,'Invoice ID','发票ID')}: {row.documentId}</p>{partner?<a href={row.partnerId&&row.mode?`/admin/reports/partner-settlement/billing?partnerId=${encodeURIComponent(row.partnerId)}&mode=${encodeURIComponent(row.mode)}`:'/admin/finance/documents?channel=PARTNER&type=INVOICE'}>{t(lang,'Open original billing records','打开原账单记录')}</a>:row.packageId?<a href={`/admin/packages/${row.packageId}/billing#invoices`}>{t(lang,'Open original billing records','打开原账单记录')}</a>:null}{row.state==='VERIFIED'?<p>{t(lang,'Invoice','发票')}: {money(row.invoiceCents!)}{partner?` · ${t(lang,'Issued credits','已开贷项')}: ${money(row.creditCents!)} · ${t(lang,'Adjusted invoice','调整后发票')}: ${money(row.adjustedInvoiceCents!)}`:''} · {t(lang,'Approved receipts','已批准收据')}: {money(row.approvedCents!)}</p>:null}<p>{t(lang,'Review basis','核对依据')}: {row.reviewNote}</p><small>{row.reviewedBy} · {formatBusinessDateTime(row.updatedAt)}</small>
 {lead&&!actor.isObserver&&row.status==='ACTIVE'?<details><summary>{t(lang,'Revoke invoice attribution','撤销发票归属')}</summary><RelationshipForm lang={lang} action={saveSalesEvidenceAction} style={{display:'grid',gap:8}}><input type="hidden" name="action" value="REVOKE"/><input type="hidden" name="leadId" value={lead.id}/><input type="hidden" name="assignmentId" value={row.id}/><input type="hidden" name="expectedUpdatedAt" value={row.updatedAt.toISOString()}/><label>{t(lang,'Reason (billing and receipts remain unchanged)','原因（账单与收据保持不变）')}<textarea name="reviewNote" required maxLength={2000}/></label><button>{t(lang,'Revoke attribution only','仅撤销归属')}</button></RelationshipForm></details>:null}</article>)}
 {canAttach?<details><summary>{partner?t(lang,'Review and attribute a partner invoice','核对并归属合作方发票'):t(lang,'Review and attribute a parent invoice','核对并归属直客发票')}</summary><p>{partner?t(lang,'Up to 100 invoices whose settlement records reference this exact student. An invoice must cover only this student and the exact partner. Unbound invoices remain in Finance for review.','显示结算记录涉及此学生的最多100张发票。发票须全部属于该学生及准确合作方，缺少关联的发票请到财务核对。'):t(lang,'Up to 100 invoices for the exact linked student. Check the source and referral evidence before selecting. Changed invoices require a new review.','显示准确关联学生最多100张发票。选择前请核对原单及转介依据，发票变化后须重新核对。')}</p>{!candidates.valid?<p role="alert">{t(lang,'Billing or approval records could not be verified. Review Finance first.','账单或审批记录无法核实，请先到财务核对。')}</p>:null}<RelationshipForm lang={lang} action={partner?savePartnerInvoiceEvidenceAction:saveParentInvoiceEvidenceAction} style={{display:'grid',gap:12}}><input type="hidden" name="leadId" value={lead.id}/><input type="hidden" name="expectedUpdatedAt" value={lead.updatedAt.toISOString()}/><label style={{display:'grid'}}>{partner?t(lang,'Exact partner invoice','准确合作方发票'):t(lang,'Exact parent invoice','准确直客发票')}<select name="invoice" defaultValue="" required style={{maxWidth:'100%'}}><option value="">{t(lang,'Select after review','核对后选择')}</option>{candidates.rows.map(c=><option key={c.id} value={`${c.id}|${c.sourceFingerprint}`} disabled={c.state!=='VERIFIED'||c.assignedElsewhere}>{c.invoiceNo} · {c.id} · {c.assignedElsewhere?t(lang,'Attributed to another lead','已归属其他商机'):t(lang,c.en,c.zh)}</option>)}</select></label><label style={{display:'grid'}}>{t(lang,'Invoice referral attribution evidence','发票转介归属核对依据')}<textarea name="reviewNote" required maxLength={2000}/></label><button disabled={!candidates.rows.some(c=>c.state==='VERIFIED'&&!c.assignedElsewhere)}>{t(lang,'Save reviewed invoice attribution','保存已核对发票归属')}</button></RelationshipForm></details>:null}
 </details>;
}
