export type OperationCoverageLevel = "DETAILED_SOP" | "MASTER_SOP" | "SYSTEM_GUIDE";

export type OperationArea = {
  code: string;
  title: string;
  owners: string[];
  level: OperationCoverageLevel;
  routePrefixes: string[];
  moduleCodes: string[];
  outcome: string;
};

export const OPERATION_AREAS: OperationArea[] = [
  {
    code: "ACCESS",
    title: "登录、首页与系统入口",
    owners: ["全体员工"],
    level: "SYSTEM_GUIDE",
    routePrefixes: [
      "/",
      "/admin/login",
      "/admin/setup",
      "/miniapp/pages/login",
      "/miniapp/pages/staff-login",
      "/miniapp/pages/staff-bind",
      "/miniapp/pages/staff-account-switch",
      "/miniapp/pages/bind",
    ],
    moduleCodes: ["SYSTEM_OPERATION_MAP", "MANAGEMENT_CONTROL_MASTER"],
    outcome: "使用正确员工账号进入对应工作台；学生和未登录用户不能进入内部培训。",
  },
  {
    code: "TRAINING",
    title: "员工培训、考试与主管验收",
    owners: ["全体员工", "主管"],
    level: "DETAILED_SOP",
    routePrefixes: ["/training"],
    moduleCodes: ["SYSTEM_OPERATION_MAP", "MANAGEMENT_CONTROL_MASTER"],
    outcome: "完成当前版本阅读、80 分测验、实操证据和主管验收。",
  },
  {
    code: "SCHOOL_APPLICATION",
    title: "学校申请服务与外部签署",
    owners: ["教务", "管理"],
    level: "DETAILED_SOP",
    routePrefixes: ["/admin/school-applications", "/admin/students/[id]/school-applications", "/school-application", "/school-application-info"],
    moduleCodes: ["SCHOOL_APPLICATION"],
    outcome: "申请服务从建档、资料、协议签署、收费到归档形成完整状态链。",
  },
  {
    code: "COMMUNICATION",
    title: "家长沟通、老师通知与反馈监督",
    owners: ["教务", "老师", "管理"],
    level: "DETAILED_SOP",
    routePrefixes: [
      "/admin/communications",
      "/admin/feedbacks",
      "/admin/miniapp-notifications",
      "/admin/teacher-notices",
      "/teacher/notices",
      "/teacher/manager-feedback",
      "/teacher/student-feedbacks",
      "/teacher/alerts",
      "/miniapp/pages/staff-communications",
      "/miniapp/pages/staff-teacher-feedbacks",
      "/miniapp/pages/feedbacks",
    ],
    moduleCodes: ["PARENT_COMMUNICATION", "MANAGEMENT_COMMUNICATION", "MANAGER_FEEDBACK", "TEACHER_DAILY"],
    outcome: "内部反馈经审核后发布给正确对象，并保留转发、更正、确认和审计记录。",
  },
  {
    code: "REPORTING",
    title: "教学报告、质量与审计报表",
    owners: ["老师", "教务", "管理", "财务"],
    level: "MASTER_SOP",
    routePrefixes: [
      "/admin/reports",
      "/teacher/midterm-reports",
      "/teacher/final-reports",
      "/final-report",
      "/miniapp/pages/staff-teacher-reports",
      "/miniapp/pages/progress",
      "/miniapp/pages/care-reports",
      "/miniapp/pages/care-report-detail",
    ],
    moduleCodes: ["TEACHER_DAILY", "MANAGEMENT_CONTROL_MASTER", "FINANCE_MASTER"],
    outcome: "报告按责任人准备、复核、发布或导出；异常记录可追溯。",
  },
  {
    code: "LEADS_GUIDE",
    title: "资源、学校指南咨询与成交交接",
    owners: ["销售", "客服", "教务"],
    level: "DETAILED_SOP",
    routePrefixes: ["/admin/leads", "/school-guide", "/teacher/lead", "/miniapp/pages/guide-", "/miniapp/pages/staff-leads"],
    moduleCodes: ["RESOURCE_HANDOFF_MASTER"],
    outcome: "咨询完成查重、跟进、评估、负责人和成交后交接。",
  },
  {
    code: "WORK_CONTROL",
    title: "工单、待办、提醒、审批与恢复",
    owners: ["教务", "管理", "财务"],
    level: "MASTER_SOP",
    routePrefixes: [
      "/admin/tickets",
      "/tickets",
      "/admin/todos",
      "/admin/alerts",
      "/admin/approvals",
      "/admin/recovery",
      "/miniapp/pages/staff-renewals",
      "/miniapp/pages/staff-issue-report",
      "/miniapp/pages/staff-approvals",
      "/miniapp/pages/staff-reminder-attention",
      "/miniapp/pages/staff-requests",
      "/miniapp/pages/staff-request-",
      "/miniapp/pages/requests",
      "/miniapp/pages/request-",
    ],
    moduleCodes: ["ACADEMIC_SCHEDULING_MASTER", "MANAGEMENT_CONTROL_MASTER", "FINANCE_MASTER"],
    outcome: "工作有负责人、状态、截止时间、完成结果、交接和异常升级。",
  },
  {
    code: "EDUTRUST",
    title: "EduTrust 课程、SSG 合同与学生证据",
    owners: ["教务", "管理"],
    level: "DETAILED_SOP",
    routePrefixes: ["/admin/edutrust"],
    moduleCodes: ["EDUTRUST_SSG"],
    outcome: "课程和合同字段通过 readiness 检查后才进入签署和证据归档。",
  },
  {
    code: "CARE",
    title: "全托管计划、执行、风险与报告",
    owners: ["教务", "管理"],
    level: "DETAILED_SOP",
    routePrefixes: ["/admin/care"],
    moduleCodes: ["FULL_CARE"],
    outcome: "计划、活动、任务、风险、覆盖安排和报告在同一学生项目内闭环。",
  },
  {
    code: "FINANCE",
    title: "财务、收据审批、工资报销与合作方",
    owners: ["财务", "管理"],
    level: "DETAILED_SOP",
    routePrefixes: [
      "/admin/finance",
      "/admin/receipts-approvals",
      "/admin/expense-claims",
      "/admin/reports/teacher-payroll",
      "/admin/reports/partner-settlement",
      "/miniapp/pages/staff-teacher-expenses",
      "/miniapp/pages/staff-teacher-payroll",
      "/miniapp/pages/finance",
    ],
    moduleCodes: ["FINANCE_MASTER", "FINANCE_PAYMENT_PROFILE", "PARTNER_CREDIT_NOTE", "XZS_SETTLEMENT"],
    outcome: "发票、付款凭证、收据、审批、工资、报销与合作方账单相互核对并可审计。",
  },
  {
    code: "PACKAGES_CONTRACTS",
    title: "合同、课包、账单与余额台账",
    owners: ["教务", "财务"],
    level: "DETAILED_SOP",
    routePrefixes: ["/admin/packages", "/contract", "/contract-intake"],
    moduleCodes: ["CONTRACT_PACKAGE_GATE_MASTER", "SHARED_PACKAGE_COURSE", "XZS_PACKAGE"],
    outcome: "首购或续费完成合同、发票审批、课包和允许排课门禁后才交接排课。",
  },
  {
    code: "SCHEDULING",
    title: "排课、班级、报名、可用时间与考勤",
    owners: ["教务", "老师"],
    level: "DETAILED_SOP",
    routePrefixes: [
      "/admin/schedule",
      "/admin/monthly-scheduling",
      "/admin/classes",
      "/admin/enrollments",
      "/admin/booking-links",
      "/booking",
      "/availability",
      "/admin/conflicts",
      "/admin/sessions",
      "/miniapp/pages/staff-schedule",
      "/miniapp/pages/staff-session-detail",
      "/miniapp/pages/staff-coordination",
      "/miniapp/pages/staff-coordination-detail",
      "/miniapp/pages/staff-first-scheduling",
      "/miniapp/pages/staff-student-scheduling",
      "/miniapp/pages/staff-monthly-scheduling",
      "/miniapp/pages/staff-monthly-scheduling-proxy",
      "/miniapp/pages/monthly-scheduling",
      "/miniapp/pages/schedule",
    ],
    moduleCodes: ["ACADEMIC_SCHEDULING_MASTER", "ATTENDANCE_EXCEPTION_MASTER"],
    outcome: "从时间收集、冲突检查、排课确认、课次到点名反馈和异常处理闭环。",
  },
  {
    code: "STUDENTS",
    title: "学生档案、入学资料与教务协同",
    owners: ["教务", "客服"],
    level: "MASTER_SOP",
    routePrefixes: [
      "/admin/students",
      "/student-intake",
      "/partner/student-intake",
      "/miniapp/pages/staff-student-workspace",
      "/miniapp/pages/students",
    ],
    moduleCodes: ["CONTRACT_PACKAGE_GATE_MASTER", "ACADEMIC_SCHEDULING_MASTER", "SCHOOL_APPLICATION"],
    outcome: "学生资料从外部收集、内部建档、课程与合同准备到后续服务交接。",
  },
  {
    code: "TEACHERS",
    title: "老师档案、课表、可用时间、授课与收款",
    owners: ["老师", "教务", "管理"],
    level: "DETAILED_SOP",
    routePrefixes: [
      "/admin/teachers",
      "/teacher",
      "/miniapp/pages/staff-teacher-leave",
      "/miniapp/pages/staff-teacher-availability",
      "/miniapp/pages/staff-teacher-history",
      "/miniapp/pages/staff-teacher-todos",
    ],
    moduleCodes: ["TEACHER_MINIAPP", "TEACHER_DAILY", "TEACHER_PAYMENT", "ATTENDANCE_EXCEPTION_MASTER"],
    outcome: "老师资料、可授课程、时间、课次、反馈、报告、工资和收款资料一致。",
  },
  {
    code: "MANAGEMENT",
    title: "账号、权限、基础资料与小程序管理",
    owners: ["管理"],
    level: "MASTER_SOP",
    routePrefixes: [
      "/admin/manager",
      "/admin/miniapp-staff",
      "/admin/campuses",
      "/admin/rooms",
      "/admin/courses",
      "/admin/student-sources",
      "/admin/student-types",
      "/admin/partners",
    ],
    moduleCodes: ["MANAGEMENT_CONTROL_MASTER", "MANAGEMENT_MINIAPP", "SYSTEM_OPERATION_MAP"],
    outcome: "账号主角色控制系统权限，培训岗位独立分配；基础资料变更有负责人和复核。",
  },
  {
    code: "DASHBOARD",
    title: "后台与移动工作台",
    owners: ["教务", "客服", "销售", "财务", "管理"],
    level: "SYSTEM_GUIDE",
    routePrefixes: [
      "/admin",
      "/admin/mobile",
      "/miniapp/pages/staff-home",
      "/miniapp/pages/staff-action-center",
      "/miniapp/pages/staff-operations",
      "/miniapp/pages/staff-health",
      "/miniapp/pages/home",
    ],
    moduleCodes: ["SYSTEM_OPERATION_MAP", "ACADEMIC_MINIAPP", "MANAGEMENT_MINIAPP"],
    outcome: "员工从角色工作台进入待办、提醒和业务流程，不跨权限操作。",
  },
];

function prefixMatches(route: string, prefix: string) {
  if (prefix === "/") return route === "/";
  if (prefix.endsWith("-")) return route.startsWith(prefix);
  return route === prefix || route.startsWith(`${prefix}/`);
}

export function operationAreaForRoute(route: string) {
  return OPERATION_AREAS.find((area) => area.routePrefixes.some((prefix) => prefixMatches(route, prefix))) ?? null;
}
