import SalesInvoiceEvidencePanel from '../SalesInvoiceEvidencePanel';
import SalesContractEvidencePanel from '../SalesContractEvidencePanel';
import RelationshipForm from '../RelationshipForm';
import {requireResourceUser} from '@/lib/auth';
import {prisma} from '@/lib/prisma';
import {getLang,t} from '@/lib/i18n';
import {formatBusinessDateTime} from '@/lib/date-only';
import {summarizeRelationshipLeads} from '@/lib/sales-relationship-policy';
import {LEAD_STATUS_LABELS} from '@/lib/leads';
import {notFound} from 'next/navigation';
import {updateRelationshipAction,addRelationshipFollowUpAction,saveRelationshipOpportunityAction} from '../actions';
import {panel,grid,ProfileFields,OpportunityFields,Field,Area,dateInput,relationLabel} from '../fields';
export default async function RelationshipDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams?:Promise<{err?:string;ok?:string}>}){
 const actor=await requireResourceUser();const lang=await getLang(),{id}=await params,sp=await searchParams;
 const row=await prisma.salesRelationship.findUnique({where:{id},include:{leads:{orderBy:{updatedAt:'desc'}},opportunities:{orderBy:{updatedAt:'desc'}},followUps:{orderBy:{createdAt:'desc'},take:100}}});if(!row)notFound();
 const summary=summarizeRelationshipLeads(row.leads),students=row.leads.filter(l=>l.recordKind==='STUDENT');
 const hidden=<><input type="hidden" name="relationshipId" value={id}/><input type="hidden" name="expectedUpdatedAt" value={row.updatedAt.toISOString()}/></>;
 return <main style={{display:'grid',gap:16}}><a href="/admin/relationships">{t(lang,'Back to relationships','返回关系管理')}</a><header style={panel}><div>{relationLabel(lang,row.kind)} · {relationLabel(lang,row.status)}</div><h1>{row.name}</h1><p>{t(lang,'Relationship owner','关系负责人')}: {row.ownerName||t(lang,'Unassigned','未分配')}</p><p>{row.nextAction||t(lang,'Next action not set','尚未设置下一步')} · {row.nextActionDue?formatBusinessDateTime(row.nextActionDue):t(lang,'No follow-up date','未设置跟进日期')}</p><p>{[row.contactName,row.contactEmail,row.contactPhone,row.contactWechat].filter(Boolean).join(' · ')}</p>{row.note?<p style={{whiteSpace:'pre-wrap'}}>{row.note}</p>:null}</header>
 {sp?.err?<p role="alert" style={{color:'#991b1b'}}>{sp.err}</p>:null}{sp?.ok?<p role="status">{t(lang,'Saved','已保存')}</p>:null}
 <section style={grid}>{[[t(lang,'Student opportunities','学生商机'),summary.studentOpportunities],[t(lang,'Distinct linked students','已关联学生（去重）'),summary.linkedStudents],[t(lang,'Open opportunities','跟进中商机'),summary.openStudentOpportunities]].map(([label,value])=><div key={String(label)} style={panel}><div>{label}</div><strong style={{fontSize:28}}>{value}</strong></div>)}</section>
 <p>{t(lang,'Creating a student record or marking a deal Won does not verify a signed contract or payment. Review contract and receipt evidence in the existing finance workflow.','学生建档或将商机标记为成交，不代表合同及收款已核验。请通过原财务流程核对合同与收据。')}</p>
 <SalesContractEvidencePanel actor={actor} lang={lang} scope={{relationshipId:id}}/>
 <SalesInvoiceEvidencePanel actor={actor} lang={lang} scope={{relationshipId:id}}/>
 <SalesInvoiceEvidencePanel channel="PARTNER" actor={actor} lang={lang} scope={{relationshipId:id}}/>
 <section style={panel}><h2>{t(lang,'Referred students & deals','转介学生与商机')}</h2><a href={`/admin/leads/new?relationshipId=${id}`}>{t(lang,'Add student opportunity','新增学生商机')}</a> · <a href="/admin/leads">{t(lang,'Review and link an existing record','核对并关联原有记录')}</a>{students.length?<div style={{overflowX:'auto'}}><table cellPadding={10} style={{width:'100%',textAlign:'left'}}><thead><tr>{[t(lang,'Student opportunity','学生商机'),t(lang,'Deal status','商机状态'),t(lang,'Deal owner','商机负责人'),t(lang,'Next action','下一步'),t(lang,'Follow-up date','跟进日期')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{students.map(lead=><tr key={lead.id}><td><a href={`/admin/leads/${lead.id}`}>{lead.studentName} · {lead.leadNo}</a>{lead.isArchived?<small> · {t(lang,'Archived','已归档')}</small>:null}</td><td>{LEAD_STATUS_LABELS[lead.status]?t(lang,LEAD_STATUS_LABELS[lead.status].en,LEAD_STATUS_LABELS[lead.status].zh):lead.status}</td><td>{lead.ownerName||'—'}</td><td>{lead.nextAction||'—'}</td><td>{lead.nextActionDue?formatBusinessDateTime(lead.nextActionDue):'—'}</td></tr>)}</tbody></table></div>:<p>{t(lang,'No student opportunities linked yet. Each student will keep an independent deal status.','暂无关联学生商机。每位学生的成交进度独立维护。')}</p>}</section>
 <section style={panel}><h2>{t(lang,'Relationship follow-up','关系跟进')}</h2><RelationshipForm lang={lang} action={addRelationshipFollowUpAction} style={{display:'grid',gap:12}}>{hidden}<div style={grid}><Field lang={lang} name="channel" en="Channel" zh="沟通渠道" required/><Field lang={lang} name="nextAction" en="Next action" zh="下一步" value={row.nextAction??''}/><Field lang={lang} name="nextActionDue" en="Next follow-up (Singapore)" zh="下次跟进（新加坡时间）" type="datetime-local" value={dateInput(row.nextActionDue)}/></div><Area lang={lang} name="content" en="What was discussed and agreed" zh="沟通内容与约定" required/><button>{t(lang,'Save follow-up','保存跟进')}</button></RelationshipForm></section>
 <section style={panel}><h2>{t(lang,'Cooperation projects & future activities','合作项目与未来活动')}</h2><p>{t(lang,'These projects are separate from student deals. Estimated value is not revenue received.','合作项目与学生商机分别维护，潜在金额不计作实收。')}</p>{row.opportunities.map(item=><details key={item.id} style={{...panel,marginBottom:10}}><summary>{item.title} · {relationLabel(lang,item.status)} · {item.ownerName||t(lang,'Unassigned','未分配')}{item.nextActionDue?` · ${formatBusinessDateTime(item.nextActionDue)}`:''}</summary><p>{item.nextAction}</p><RelationshipForm lang={lang} action={saveRelationshipOpportunityAction} style={{display:'grid',gap:12}}><input type="hidden" name="relationshipId" value={id}/><input type="hidden" name="opportunityId" value={item.id}/><input type="hidden" name="expectedUpdatedAt" value={item.updatedAt.toISOString()}/><OpportunityFields lang={lang} row={item}/><button>{t(lang,'Save project','保存项目')}</button></RelationshipForm></details>)}<details><summary>{t(lang,'Add cooperation project','新增合作项目')}</summary><RelationshipForm lang={lang} action={saveRelationshipOpportunityAction} style={{display:'grid',gap:12,marginTop:12}}><input type="hidden" name="relationshipId" value={id}/><OpportunityFields lang={lang}/><button>{t(lang,'Create project','创建项目')}</button></RelationshipForm></details></section>
 <details style={panel}><summary>{t(lang,'Edit relationship profile','编辑关系档案')}</summary><RelationshipForm lang={lang} action={updateRelationshipAction} style={{display:'grid',gap:12,marginTop:12}}>{hidden}<ProfileFields lang={lang} row={row}/><button>{t(lang,'Save profile','保存档案')}</button></RelationshipForm></details>
 <details style={panel}><summary>{t(lang,`Follow-up history (${row.followUps.length}, latest 100)`,`跟进历史（${row.followUps.length}，最近100条）`)}</summary>{row.followUps.map(f=><article key={f.id} style={{borderBottom:'1px solid #e2e8f0',padding:'12px 0'}}><strong>{formatBusinessDateTime(f.createdAt)} · {f.actorName} · {f.channel}</strong><p style={{whiteSpace:'pre-wrap'}}>{f.content}</p><p>{f.nextAction} {f.nextActionDue?formatBusinessDateTime(f.nextActionDue):''}</p></article>)}</details>
 {row.leads.some(l=>l.recordKind!=='STUDENT')?<details style={panel}><summary>{t(lang,'Original relationship records','原始关系记录')}</summary>{row.leads.filter(l=>l.recordKind!=='STUDENT').map(l=><p key={l.id}><a href={`/admin/leads/${l.id}`}>{l.leadNo} · {l.studentName}</a> · {l.relationshipReviewNote}</p>)}</details>:null}</main>;
}
