import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';
import {accessParentCareReport} from '../../lib/parent-care-reports';
import {createParentCareQuestion,answerParentCareQuestion,readParentCareQuestions,closeParentCareQuestion} from '../../lib/care-operations';
import {createParentPortalSession} from '../../lib/parent-portal';
async function main(){
 for(const key of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[key]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 const owner=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}});
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r454-fixture.json','utf8')),base='http://127.0.0.1:3149',path='/api/miniapp/students/'+f.studentId+'/care-reports/'+f.reportId,headers={Authorization:'Bearer '+f.token,'Content-Type':'application/json'};
  const get=await fetch(base+path,{headers});assert.equal(get.status,200);const text=await get.text();assert(!text.includes('ISOLATED-PRIVATE'));assert(!text.includes('internalNote'));
  const pdf=await fetch(base+path+'/pdf',{headers});assert.equal(pdf.status,200);assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,4).toString(),'%PDF');
  const ack=await(await fetch(base+path,{method:'POST',headers})).json();const again=await(await fetch(base+path,{method:'POST',headers})).json();assert.deepEqual(ack,again);
  const ask=await fetch(base+path+'/questions',{method:'POST',headers,body:JSON.stringify({question:'Isolated HTTP follow-up'})});assert.equal(ask.status,200);const qid=(await ask.json()).id;
  const staffToken=randomUUID();await prisma.authSession.create({data:{userId:owner.id,token:staffToken,expiresAt:new Date(Date.now()+3600000)}});const staffCookie='ts_admin_session='+staffToken,staffUrl=base+'/admin/care/'+f.engagementId+'/reports/'+f.reportId;
  let html='';try { for(const language of ['EN','ZH','BILINGUAL'] as const){await prisma.user.update({where:{id:owner.id},data:{language}});html=await(await fetch(staffUrl,{headers:{Cookie:staffCookie}})).text();assert(html.includes(language==='EN'?'Saved responses appear in the parent portal':'保存的回复显示在家长端'));} } finally {await prisma.user.update({where:{id:owner.id},data:{language:owner.language}});}
  const form=(html.match(/<form\b[^>]*>[\s\S]*?<\/form>/g)||[]).find(s=>s.includes('type="hidden" name="questionId"')&&s.includes(qid));assert(form);
  const fields=[...form.matchAll(/<input[^>]+name="([^"]+)"[^>]*value="([^"]*)"/g)].map(m=>[m[1],m[2].replaceAll('&quot;','"').replaceAll('&amp;','&')]);const action=form.match(/name="(\$ACTION_(?:REF|ID)_[^"]+)"/);assert(action);const data=new FormData();for(const [key,value]of fields)data.set(key,value);data.set(action[1],'');data.set('response','Isolated portal response');
  const saved=await fetch(staffUrl,{method:'POST',headers:{Cookie:staffCookie,Origin:base},body:data,redirect:'manual'});assert.equal(saved.status,303);assert.equal((await prisma.careParentQuestion.findUniqueOrThrow({where:{id:qid}})).status,'ANSWERED');
  assert.equal((await fetch(base+path+'/questions',{headers})).status,200);
  const close=()=>fetch(base+path+'/questions/'+qid,{method:'POST',headers});assert.equal((await close()).status,200);assert.equal((await close()).status,200);
  const wrong=await fetch(base+path.replace(f.reportId,f.otherReportId)+'/questions/'+qid,{method:'POST',headers});assert.equal(wrong.status,400);
  await prisma.careUniversityProfile.update({where:{engagementId:f.engagementId},data:{studentConsentStatus:'WITHDRAWN'}});
  for(const suffix of ['', '/pdf'])assert.equal((await fetch(base+path+suffix,{headers})).status,404);
  assert.equal((await fetch(base+path,{method:'POST',headers})).status,404);assert.equal((await fetch(base+path+'/questions',{method:'POST',headers,body:JSON.stringify({question:'Denied'})})).status,400);
  await prisma.careUniversityProfile.update({where:{engagementId:f.engagementId},data:{studentConsentStatus:'GRANTED'}});
  console.log(JSON.stringify({passed:true,parentDetailPdfAckQuestionClose:true,staffFormAndThreeLanguages:true,repeatAckAndClose:true,wrongReportDenied:true,withdrawalDenied:true,internalNoteExcluded:true}));return;
 }
 const student=await prisma.student.create({data:{name:'Isolated parent delivery '+randomUUID().slice(0,6)}}),parent=await prisma.parentAccount.create({data:{name:'Isolated parent'}});
 const link=await prisma.parentStudentLink.create({data:{parentId:parent.id,studentId:student.id,canViewReports:true}});
 const project=await prisma.careEngagement.create({data:{studentId:student.id,programType:'UNIVERSITY_GROWTH',status:'ACTIVE',scopeJson:[],createdByUserId:owner.id,caseOwnerUserId:owner.id,universityProfile:{create:{studentConsentStatus:'GRANTED',parentVisibilityJson:{sectionIds:['formal_reports']}}}}});
 const makeReport=(start:string)=>prisma.careReport.create({data:{studentId:student.id,engagementId:project.id,reportType:'MONTHLY',status:'PUBLISHED',periodLabel:'Isolated',periodStart:new Date(start),periodEnd:new Date('2048-01-31'),title:'Isolated report',overallSummary:'Reviewed progress',actionsCompleted:'Review',nextPlan:'Next review',preparedByUserId:owner.id,approvedByUserId:owner.id,publishedAt:new Date(),internalNote:'ISOLATED-PRIVATE'}});
 const report=await makeReport('2048-01-01'),other=await makeReport('2048-01-02'),scope={parentId:parent.id,studentId:student.id,reportId:report.id};
 const baseline={ledger:await prisma.packageTxn.count(),outbox:await prisma.miniappNotificationOutbox.count()};
 let fail='VIEW_CARE_REPORT';prisma.$use(async(p,next)=>{if(['ParentPortalAudit','AuditLog'].includes(p.model||'')&&p.action==='create'&&p.args.data.action===fail)throw Error('forced portal audit failure');return next(p);});
 await assert.rejects(accessParentCareReport({...scope,mode:'VIEW'}),/forced portal audit/);assert.equal(await prisma.careReportView.count({where:{reportId:report.id}}),0);fail='';
 const viewed=await accessParentCareReport({...scope,mode:'VIEW'});assert(viewed);fail='ACKNOWLEDGE_CARE_REPORT';await assert.rejects(accessParentCareReport({...scope,mode:'ACK'}),/forced portal audit/);assert.deepEqual(await prisma.careReportView.findUnique({where:{id:viewed.view.id}}),viewed.view);fail='';
 const ack=await Promise.all([accessParentCareReport({...scope,mode:'ACK'}),accessParentCareReport({...scope,mode:'ACK'})]);assert(ack[0]&&ack[1]);assert.deepEqual(ack[0].view.acknowledgedAt,ack[1].view.acknowledgedAt);assert.equal(await prisma.parentPortalAudit.count({where:{targetId:report.id,action:'ACKNOWLEDGE_CARE_REPORT'}}),1);assert.deepEqual(ack[0].view.firstViewedAt,viewed.view.firstViewedAt);
 const a=await accessParentCareReport({...scope,mode:'PDF'});assert.equal(a!.view.viewCount,2);
 await prisma.parentStudentLink.update({where:{id:link.id},data:{canViewReports:false}});assert.equal(await accessParentCareReport({...scope,mode:'ACK'}),null);await assert.rejects(createParentCareQuestion({...scope,question:'Denied'}));await prisma.parentStudentLink.update({where:{id:link.id},data:{canViewReports:true}});
 await prisma.parentAccount.update({where:{id:parent.id},data:{status:'DISABLED'}});assert.equal(await accessParentCareReport({...scope,mode:'VIEW'}),null);await prisma.parentAccount.update({where:{id:parent.id},data:{status:'ACTIVE'}});
 const questionCount=await prisma.careParentQuestion.count(),taskCount=await prisma.careTask.count();fail='ASK_CARE_REPORT_QUESTION';await assert.rejects(createParentCareQuestion({...scope,question:'Rollback'}),/forced portal audit/);assert.equal(await prisma.careParentQuestion.count(),questionCount);assert.equal(await prisma.careTask.count(),taskCount);fail='';
 const question=await createParentCareQuestion({...scope,question:'Please clarify progress'}),answer={actor:owner,engagementId:project.id,reportId:report.id,questionId:question.id,expectedRespondedAt:'',response:'Review confirmed in portal'};
 const before=await prisma.careTask.findUniqueOrThrow({where:{id:question.careTaskId!}});fail='ANSWER_PARENT_QUESTION';await assert.rejects(answerParentCareQuestion(answer),/forced portal audit/);assert.deepEqual(await prisma.careTask.findUniqueOrThrow({where:{id:before.id}}),before);assert.equal((await prisma.careParentQuestion.findUniqueOrThrow({where:{id:question.id}})).status,'OPEN');fail='';
 const observer=await prisma.user.findFirstOrThrow({where:{name:'Policy OBSERVER'}});await assert.rejects(answerParentCareQuestion({...answer,actor:observer}),/Read-only/);await assert.rejects(answerParentCareQuestion({...answer,reportId:other.id}),/not found in this report/);
 await answerParentCareQuestion(answer);const answered=await prisma.careParentQuestion.findUniqueOrThrow({where:{id:question.id}});await answerParentCareQuestion(answer);assert.deepEqual(await prisma.careParentQuestion.findUniqueOrThrow({where:{id:question.id}}),answered);await assert.rejects(answerParentCareQuestion({...answer,response:'Stale overwrite'}),/Response changed/);
 fail='VIEW_CARE_REPORT_RESPONSE';await assert.rejects(readParentCareQuestions(scope),/forced portal audit/);assert.equal((await prisma.careParentQuestion.findUniqueOrThrow({where:{id:question.id}})).parentViewedResponseAt,null);fail='';const read=await readParentCareQuestions(scope);const reread=await readParentCareQuestions(scope);assert.deepEqual(read[0].parentViewedResponseAt,reread[0].parentViewedResponseAt);
 await assert.rejects(closeParentCareQuestion({...scope,reportId:other.id,questionId:question.id}),/not found in this report/);fail='CLOSE_CARE_REPORT_QUESTION';await assert.rejects(closeParentCareQuestion({...scope,questionId:question.id}),/forced portal audit/);assert.equal((await prisma.careParentQuestion.findUniqueOrThrow({where:{id:question.id}})).status,'ANSWERED');fail='';
 await Promise.all([closeParentCareQuestion({...scope,questionId:question.id}),closeParentCareQuestion({...scope,questionId:question.id})]);assert.equal(await prisma.parentPortalAudit.count({where:{targetId:question.id,action:'CLOSE_CARE_REPORT_QUESTION'}}),1);
 const closed=await prisma.careParentQuestion.findUniqueOrThrow({where:{id:question.id}});assert.deepEqual(closed.parentViewedResponseAt,read[0].parentViewedResponseAt);await assert.rejects(answerParentCareQuestion(answer),/Closed/);
 // Consent revoked between the first report reference and locked profile read cannot record a stale view.
 let reached!:()=>void,resume!:()=>void,paused=false;const gate=new Promise<void>(r=>resume=r),ready=new Promise<void>(r=>reached=r);
 prisma.$use(async(p,next)=>{if(!paused&&p.action==='queryRaw'&&JSON.stringify(p.args).includes('CareUniversityProfile')){paused=true;reached();await gate;}return next(p);});
 const viewBefore=await prisma.careReportView.findUniqueOrThrow({where:{id:viewed.view.id}});const pending=accessParentCareReport({...scope,mode:'VIEW'});await ready;await prisma.careUniversityProfile.update({where:{engagementId:project.id},data:{studentConsentStatus:'WITHDRAWN'}});resume();assert.equal(await pending,null);assert.deepEqual(await prisma.careReportView.findUniqueOrThrow({where:{id:viewed.view.id}}),viewBefore);await assert.rejects(createParentCareQuestion({...scope,question:'Denied consent'}));await assert.rejects(closeParentCareQuestion({...scope,questionId:question.id}));await prisma.careUniversityProfile.update({where:{engagementId:project.id},data:{studentConsentStatus:'GRANTED'}});
 assert.equal(await prisma.packageTxn.count(),baseline.ledger);assert.equal(await prisma.miniappNotificationOutbox.count(),baseline.outbox);
 const session=await createParentPortalSession(parent.id);writeFileSync('/tmp/sgt-r454-fixture.json',JSON.stringify({...scope,engagementId:project.id,otherReportId:other.id,token:session.token}));
 console.log(JSON.stringify({passed:true,atomicViewAckQuestionReplyReadClose:true,firstTimestampsAndAuditOnce:true,currentParentLinkConsent:true,exactReportScope:true,observerAndStaleReplyDenied:true,consentRaceRejected:true,noLedgerOrOutboxWrites:true}));
}
const watchdog=setTimeout(()=>{throw Error('Care parent UAT timed out');},30000);main().finally(()=>{clearTimeout(watchdog);return prisma.$disconnect();});
