import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';
import {createCareReportDraft,updateCareReportDraft,changeCareReportStatus} from '../../lib/care-reports';
import {getParentCareReport} from '../../lib/parent-care-reports';
import {createParentPortalSession} from '../../lib/parent-portal';
async function main(){
 for(const key of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[key]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 const owner=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}});
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r452-fixture.json','utf8')),base='http://127.0.0.1:3149',path='/api/miniapp/students/'+f.studentId+'/care-reports/'+f.reportId,headers={Authorization:'Bearer '+f.parentToken};
  const cookie=async(userId:string)=>{const token=randomUUID();await prisma.authSession.create({data:{userId,token,expiresAt:new Date(Date.now()+3600000)}});return 'ts_admin_session='+token;};
  const staffUrl=base+'/admin/care/'+f.engagementId+'/reports/'+f.reportId,ownerCookie=await cookie(owner.id),html=await(await fetch(staffUrl,{headers:{Cookie:ownerCookie}})).text();
  const form=(html.match(/<form\b[^>]*>[\s\S]*?<\/form>/g)||[]).find(s=>s.includes('value="REVOKED"'));assert(form);
  const fields=[...form.matchAll(/<input[^>]+name="([^"]+)"[^>]*value="([^"]*)"/g)].map(m=>[m[1],m[2].replaceAll('&quot;','"').replaceAll('&amp;','&')]);const action=form.match(/name="(\$ACTION_REF_[^"]+)"/);assert(action);
  for(const id of [f.coordinatorId,(await prisma.user.findFirstOrThrow({where:{name:'Policy OBSERVER'}})).id]){const data=new FormData();for(const [key,value]of fields)data.set(key,value);data.set(action[1],'');data.set('reviewNote','Isolated unauthorized attempt');const denied=await fetch(staffUrl,{method:'POST',headers:{Cookie:await cookie(id),Origin:base},body:data,redirect:'manual'});assert([303,307,403].includes(denied.status));assert.equal((await prisma.careReport.findUniqueOrThrow({where:{id:f.reportId}})).status,'PUBLISHED');}
  const res=await fetch(base+path,{headers});assert.equal(res.status,200);const body=await res.text();assert(!body.includes('PRIVATE-ISOLATED-NOTE'));assert(!body.includes('internalNote'));
  const pdf=await fetch(base+path+'/pdf',{headers});assert.equal(pdf.status,200);assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,4).toString(),'%PDF');
  assert.equal((await fetch(base+path,{method:'POST',headers})).status,200);
  await prisma.careUniversityProfile.update({where:{engagementId:f.engagementId},data:{studentConsentStatus:'WITHDRAWN'}});assert.equal((await fetch(base+path,{headers})).status,404);assert.equal((await fetch(base+path+'/pdf',{headers})).status,404);await prisma.careUniversityProfile.update({where:{engagementId:f.engagementId},data:{studentConsentStatus:'GRANTED'}});
  const r=await prisma.careReport.findUniqueOrThrow({where:{id:f.reportId}});await changeCareReportStatus({actor:owner,engagementId:f.engagementId,reportId:r.id,version:r.version,nextStatus:'REVOKED',reviewNote:'Isolated delivery withdrawal'});assert.equal((await fetch(base+path,{headers})).status,404);
  console.log(JSON.stringify({passed:true,staffCoordinatorAndLegacyObserverDenied:true,parentDeliveryAndPdf:true,internalNoteExcluded:true,parentAcknowledgement:true,consentWithdrawalAndRevocationHideReport:true}));return;
 }
 const user=async(role:'CS'|'SALES',name:string,care=true)=>prisma.user.create({data:{name,email:randomUUID()+'@example.invalid',role,passwordHash:'isolated',passwordSalt:'isolated',...(care?{workspaceAccesses:{create:{workspace:'CARE'}}}:{})}});
 const coordinator=await user('CS','Isolated coordinator'),reviewer=await user('CS','Isolated reviewer'),ops=await user('SALES','Isolated operations admin',false);await prisma.operationsAdminAcl.create({data:{email:ops.email}});
 const student=await prisma.student.create({data:{name:'Isolated care delivery '+randomUUID().slice(0,6)}}),engagement=await prisma.careEngagement.create({data:{studentId:student.id,programType:'UNIVERSITY_GROWTH',status:'ACTIVE',scopeJson:[],createdByUserId:owner.id,universityProfile:{create:{studentConsentStatus:'GRANTED',parentVisibilityJson:{sectionIds:['formal_reports']}}}}});
 await prisma.careEngagementMember.create({data:{engagementId:engagement.id,userId:coordinator.id,role:'COORDINATOR',assignedByUserId:owner.id}});const membership=await prisma.careEngagementMember.create({data:{engagementId:engagement.id,userId:reviewer.id,role:'REVIEWER',assignedByUserId:owner.id}});
 await prisma.careActivity.create({data:{studentId:student.id,engagementId:engagement.id,category:'ACADEMIC',occurredAt:new Date('2048-08-03'),title:'Isolated progress',factEvidence:'Reviewed assessment evidence',createdByUserId:owner.id,updatedByUserId:owner.id}});
 const createInput={actor:coordinator,engagementId:engagement.id,reportType:'MONTHLY',periodLabel:'August2048',periodStart:'2048-08-01',periodEnd:'2048-08-31'};
 let failAction='CREATE_DRAFT';prisma.$use(async(p,next)=>{if(p.model==='AuditLog'&&p.action==='create'&&p.args.data.module==='CARE_REPORT'&&p.args.data.action===failAction)throw Error('forced report audit failure');return next(p);});
 await assert.rejects(createCareReportDraft(createInput),/forced report audit/);assert.equal(await prisma.careReport.count({where:{engagementId:engagement.id}}),0);failAction='';const report=await createCareReportDraft(createInput);const snap=()=>prisma.careReport.findUniqueOrThrow({where:{id:report.id}});
 const draftInput={actor:coordinator,engagementId:engagement.id,reportId:report.id,version:report.version,title:'Isolated reviewed report',riskLevel:'LOW',overallSummary:'Progress checked against assessment',academicSummary:'Assessment reviewed',schoolSummary:'',lifeSummary:'',riskSummary:'',actionsCompleted:'Assessment reviewed with student',evidenceSummary:'Assessment reference',nextPlan:'Review next assessment next month',studentActions:'',parentActions:'',internalNote:'PRIVATE-ISOLATED-NOTE'};
 let before=await snap();failAction='UPDATE_DRAFT';await assert.rejects(updateCareReportDraft(draftInput),/forced report audit/);assert.deepEqual(await snap(),before);failAction='';await updateCareReportDraft(draftInput);
 const change=async(nextStatus:'SUBMITTED'|'RETURNED'|'APPROVED'|'PUBLISHED'|'REVOKED',actor=reviewer,note='Isolated review')=>{const row=await snap();return changeCareReportStatus({actor,engagementId:engagement.id,reportId:report.id,version:row.version,nextStatus,reviewNote:note});};
 await change('SUBMITTED',coordinator);await assert.rejects(change('APPROVED',{...coordinator,role:'ADMIN'}),/assigned reviewer/);await change('RETURNED');await updateCareReportDraft({...draftInput,version:(await snap()).version});await change('SUBMITTED',coordinator);await change('APPROVED',ops);
 const observer=await prisma.user.findFirstOrThrow({where:{name:'Policy OBSERVER'}});await assert.rejects(change('PUBLISHED',{...observer,role:'ADMIN'}),/Read-only/);
 await prisma.careEngagementMember.update({where:{id:membership.id},data:{isActive:false}});await assert.rejects(change('PUBLISHED'),/no longer have permission/);await prisma.careEngagementMember.update({where:{id:membership.id},data:{isActive:true}});
 await prisma.careUniversityProfile.update({where:{engagementId:engagement.id},data:{studentConsentStatus:'WITHDRAWN'}});await assert.rejects(change('PUBLISHED'),/Student consent/);await prisma.careUniversityProfile.update({where:{engagementId:engagement.id},data:{studentConsentStatus:'GRANTED',parentVisibilityJson:{sectionIds:[]}}});await assert.rejects(change('PUBLISHED'),/Student consent/);await prisma.careUniversityProfile.update({where:{engagementId:engagement.id},data:{parentVisibilityJson:{sectionIds:['formal_reports']}}});
 before=await snap();const dueBefore=(await prisma.careEngagement.findUniqueOrThrow({where:{id:engagement.id}})).nextReportDueAt;failAction='STATUS_PUBLISHED';await assert.rejects(change('PUBLISHED'),/forced report audit/);assert.deepEqual(await snap(),before);assert.deepEqual((await prisma.careEngagement.findUniqueOrThrow({where:{id:engagement.id}})).nextReportDueAt,dueBefore);failAction='';
 // A consent change after transaction start but before its locked read cannot publish stale consent.
 let reached!:()=>void,release!:()=>void,paused=false;const gate=new Promise<void>(r=>release=r),read=new Promise<void>(r=>reached=r);prisma.$use(async(p,next)=>{if(!paused&&p.action==='queryRaw'&&JSON.stringify(p.args).includes("CareUniversityProfile")){paused=true;reached();await gate;}return next(p);});
 const pending=change('PUBLISHED');await read;await prisma.careUniversityProfile.update({where:{engagementId:engagement.id},data:{studentConsentStatus:'WITHDRAWN'}});release();await assert.rejects(pending);assert.deepEqual(await snap(),before);await prisma.careUniversityProfile.update({where:{engagementId:engagement.id},data:{studentConsentStatus:'GRANTED'}});
 let memberReached!:()=>void,memberRelease!:()=>void,memberPaused=false;const memberGate=new Promise<void>(r=>memberRelease=r),memberRead=new Promise<void>(r=>memberReached=r);
 prisma.$use(async(p,next)=>{if(!memberPaused&&p.action==='queryRaw'&&JSON.stringify(p.args).includes('CareEngagementMember')){memberPaused=true;memberReached();await memberGate;}return next(p);});const memberPending=change('PUBLISHED');await memberRead;await prisma.careEngagementMember.update({where:{id:membership.id},data:{isActive:false}});memberRelease();await assert.rejects(memberPending);assert.deepEqual(await snap(),before);await prisma.careEngagementMember.update({where:{id:membership.id},data:{isActive:true}});
 const baseline={ledger:await prisma.packageTxn.count(),outbox:await prisma.miniappNotificationOutbox.count()};const input={actor:reviewer,engagementId:engagement.id,reportId:report.id,version:before.version,nextStatus:'PUBLISHED' as const};const race=await Promise.allSettled([changeCareReportStatus(input),changeCareReportStatus(input)]);assert.equal(race.filter(r=>r.status==='fulfilled').length,1);assert.equal(await prisma.auditLog.count({where:{entityId:report.id,action:'STATUS_PUBLISHED'}}),1);assert(await getParentCareReport(report.id,student.id));assert.equal(await getParentCareReport(report.id,'wrong-student'),null);assert.equal(await prisma.packageTxn.count(),baseline.ledger);assert.equal(await prisma.miniappNotificationOutbox.count(),baseline.outbox);
 const parent=await prisma.parentAccount.create({data:{name:'Isolated care parent'}});await prisma.parentStudentLink.create({data:{parentId:parent.id,studentId:student.id,canViewReports:true}});const session=await createParentPortalSession(parent.id);writeFileSync('/tmp/sgt-r452-fixture.json',JSON.stringify({coordinatorId:coordinator.id,engagementId:engagement.id,studentId:student.id,reportId:report.id,parentToken:session.token}));console.log(JSON.stringify({passed:true,fullDraftReturnApprovePublishWorkflow:true,freshRoleMembershipConsentGuards:true,observerAndSpoofedRoleDenied:true,operationsAdminReviewMatchesUI:true,auditRollbackAndDueDateAtomic:true,consentAndMembershipRacesRejected:true,concurrentPublicationOnce:true,noLedgerOrOutboxWrites:true}));
}
const watchdog=setTimeout(()=>{throw Error('Care UAT did not reach completion within 30 seconds');},30000);
main().finally(()=>{clearTimeout(watchdog);return prisma.$disconnect();});
