import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';
import * as care from '../../lib/care-management';
import * as ops from '../../lib/care-operations';
async function main(){
 for(const key of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[key]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 const owner=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}}),observer=await prisma.user.findFirstOrThrow({where:{name:'Policy OBSERVER'}});
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r455-fixture.json','utf8')),base='http://127.0.0.1:3149',url=base+'/admin/care/'+f.engagementId+'/operations';
  const cookie=async(userId:string)=>{const token=randomUUID();await prisma.authSession.create({data:{userId,token,expiresAt:new Date(Date.now()+3600000)}});return 'ts_admin_session='+token;};
  const ownerCookie=await cookie(owner.id),html=await(await fetch(url,{headers:{Cookie:ownerCookie}})).text();
  const form=(html.match(/<form\b[^>]*>[\s\S]*?<\/form>/g)||[]).find(s=>s.includes('name="facts"')&&s.includes('name="immediateAction"'));assert(form);
  const fields=[...form.matchAll(/<input[^>]+name="([^"]+)"[^>]*value="([^"]*)"/g)].map(m=>[m[1],m[2].replaceAll('&quot;','"').replaceAll('&amp;','&')]);const action=form.match(/name="(\$ACTION_(?:REF|ID)_[^"]+)"/);assert(action);
  const body=()=>{const d=new FormData();for(const [key,value]of fields)d.set(key,value);d.set(action[1],'');for(const [k,v]of Object.entries({title:'Isolated HTTP risk',riskLevel:'LOW',facts:'Observed',immediateAction:'Review',ownerUserId:f.memberId,backupOwnerUserId:'',detectedAt:'2048-04-01T10:00',publicSummary:''}))d.set(k,v);return d;};
  const before=await prisma.careRiskCase.count({where:{engagementId:f.engagementId}});const denied=await fetch(url,{method:'POST',headers:{Cookie:await cookie(observer.id),Origin:base},body:body(),redirect:'manual'});assert([303,307,403].includes(denied.status));assert.equal(await prisma.careRiskCase.count({where:{engagementId:f.engagementId}}),before);
  const accepted=await fetch(url,{method:'POST',headers:{Cookie:await cookie(f.memberId),Origin:base},body:body(),redirect:'manual'});assert.equal(accepted.status,303);assert.equal(await prisma.careRiskCase.count({where:{engagementId:f.engagementId}}),before+1);
  console.log(JSON.stringify({passed:true,legacyObserverFormDenied:true,assignedMemberFormAccepted:true}));return;
 }
 const makeUser=()=>prisma.user.create({data:{name:'Isolated care operator',email:randomUUID()+'@example.invalid',role:'CS',passwordHash:'isolated',passwordSalt:'isolated',workspaceAccesses:{create:{workspace:'CARE'}}}});
 const member=await makeUser(),outsider=await makeUser(),student=await prisma.student.create({data:{name:'Isolated Care staff '+randomUUID().slice(0,6)}});
 const create={studentId:student.id,programType:'UNIVERSITY_GROWTH',startDate:'2048-01-01',caseOwnerUserId:member.id,reviewerUserId:owner.id,scopeIds:['university_semester_planning']};
 let failAudit=false;prisma.$use(async(p,next)=>{if(failAudit&&p.model==='AuditLog'&&p.action==='create'&&p.args.data.module==='CARE_MANAGEMENT')throw Error('forced Care audit failure');return next(p);});
 failAudit=true;await assert.rejects(care.createCareEngagement({...create,actor:owner}),/forced Care audit/);assert.equal(await prisma.careEngagement.count({where:{studentId:student.id}}),0);failAudit=false;
 const project=await care.createCareEngagement({...create,actor:owner});await prisma.careEngagement.update({where:{id:project.id},data:{status:'ACTIVE'}});
 const membership=await prisma.careEngagementMember.findFirstOrThrow({where:{engagementId:project.id,userId:member.id,isActive:true}});
 const scope={engagementId:project.id},config={...scope,version:1,startDate:'2048-01-01',endDate:'2049-01-01',caseOwnerUserId:member.id,reviewerUserId:owner.id,scopeIds:create.scopeIds};
 const profile={...scope,version:0,institution:'Isolated university',degreeProgram:'Degree',currentAcademicYear:'1',currentTerm:'1',expectedGraduationDate:'2050-01-01',currentGpaLabel:'3/4',targetGpaLabel:'4/4',studentConsentStatus:'GRANTED',parentVisibilityIds:['academic_progress'],consentNote:'Isolated consent evidence'};
 const plan={...scope,periodLabel:'2048',periodStart:'2048-01-01',periodEnd:'2048-12-31',baseline:'Initial',goals:'Goal',successCriteria:'Evidence',actionPlan:'Review'};
 const activity={...scope,category:'ACADEMIC',subtype:'',occurredAt:'2048-01-02',title:'Isolated assessment',factEvidence:'Reviewed assessment',professionalJudgment:'',actionTaken:'',outcomeVerification:'',nextAction:'',nextActionDue:'',riskLevel:'LOW',ownerUserId:member.id,internalNote:'',audience:'PARENT',publicSummary:'Assessment reviewed'};
 const attachment={...scope,category:'ACADEMIC_REPORT',title:'Isolated evidence',audience:'INTERNAL_ONLY',filePath:'/isolated/not-a-real-upload.pdf',originalFileName:'isolated.pdf',fileSizeBytes:1};
 const risk={...scope,title:'Isolated risk',riskLevel:'LOW',facts:'Observed facts',immediateAction:'Review',ownerUserId:member.id,backupOwnerUserId:'',detectedAt:'2048-01-02',parentVisible:false,publicSummary:''};
 const coverage={...scope,primaryUserId:member.id,backupUserId:owner.id,startAt:'2048-02-01',endAt:'2048-02-02',reason:'Planned leave',handoverSummary:'Handover',criticalActions:'Follow up'};
 const review={...scope,periodLabel:'2048-01',periodStart:'2048-01-01',periodEnd:'2048-01-31',goalsSummary:'Goals',deliverySummary:'Delivery',outcomeSummary:'Outcome',evidenceSummary:'Evidence',continuationRecommendation:'CONTINUE',nextStagePlan:'Next',internalCommercialNote:''};
 type Actor=typeof owner;
 const calls: Array<(actor:Actor)=>Promise<unknown>>=[
 a=>care.createCareEngagement({...create,actor:a}),a=>care.changeCareEngagementStatus({...scope,actor:a,version:1,nextStatus:'PAUSED'}),a=>care.updateCareEngagementConfig({...config,actor:a}),a=>care.upsertCareUniversityProfile({...profile,actor:a}),a=>care.addCarePlan({...plan,actor:a}),a=>care.addCareActivity({...activity,actor:a}),a=>care.changeCareActivityPublicationStatus({...scope,actor:a,activityId:'none',version:1,nextStatus:'PUBLISHED'}),a=>care.createCareAttachment({...attachment,actor:a}),a=>care.setCareAttachmentArchived({...scope,actor:a,attachmentId:'none',version:1,archived:true}),a=>ops.createCareRiskCase({...risk,actor:a}),a=>ops.changeCareRiskCaseStatus({...scope,actor:a,riskCaseId:'none',version:1,nextStatus:'ACKNOWLEDGED',resolutionEvidence:''}),a=>ops.createCareCoveragePeriod({...coverage,actor:a}),a=>ops.changeCareCoverageStatus({...scope,actor:a,coverageId:'none',version:1,nextStatus:'ACTIVE'}),a=>ops.createCareServiceReview({...review,actor:a}),a=>ops.updateCareServiceReview({...review,actor:a,reviewId:'none',version:1}),a=>ops.changeCareServiceReviewStatus({...scope,actor:a,reviewId:'none',version:1,nextStatus:'SUBMITTED'})];
 const snapshot=()=>Promise.all([prisma.careEngagement.findUnique({where:{id:project.id}}),prisma.careEngagementMember.findMany({where:scope,orderBy:{id:'asc'}}),prisma.careUniversityProfile.findUnique({where:scope}),prisma.carePlan.findMany({where:scope}),prisma.careActivity.findMany({where:scope}),prisma.careAttachment.findMany({where:scope}),prisma.careRiskCase.findMany({where:scope}),prisma.careCoveragePeriod.findMany({where:scope}),prisma.careServiceReview.findMany({where:scope})]);
 let before=await snapshot();for(const fn of calls){await assert.rejects(fn({...observer,role:'ADMIN'}),/Read-only/);await assert.rejects(fn({...outsider,role:'ADMIN'}),/no longer have permission/);}assert.deepEqual(await snapshot(),before);
 await assert.rejects(care.createCareEngagement({...create,actor:member}),/no longer have permission/);await assert.rejects(care.updateCareEngagementConfig({...config,actor:member}),/Only authorized managers/);await assert.rejects(care.upsertCareUniversityProfile({...profile,actor:member}),/Only authorized managers/);
 const checked=async<T>(run:()=>Promise<T>)=>{const previous=await snapshot();failAudit=true;await assert.rejects(run(),/forced Care audit/);failAudit=false;assert.deepEqual(await snapshot(),previous);return run();};
 const baseline={ledger:await prisma.packageTxn.count(),outbox:await prisma.miniappNotificationOutbox.count()};
 await checked(()=>care.updateCareEngagementConfig({...config,actor:owner}));await checked(()=>care.upsertCareUniversityProfile({...profile,actor:owner}));await checked(()=>care.addCarePlan({...plan,actor:member}));
 const act=await checked(()=>care.addCareActivity({...activity,actor:member}));const pub={...scope,actor:owner,activityId:act.id,version:act.version,nextStatus:'PUBLISHED' as const};await assert.rejects(care.changeCareActivityPublicationStatus({...pub,actor:member}),/Only authorized managers/);
 await prisma.careUniversityProfile.update({where:scope,data:{studentConsentStatus:'WITHDRAWN'}});await assert.rejects(care.changeCareActivityPublicationStatus(pub),/Student consent/);await prisma.careUniversityProfile.update({where:scope,data:{studentConsentStatus:'GRANTED'}});await checked(()=>care.changeCareActivityPublicationStatus(pub));
 const att=await checked(()=>care.createCareAttachment({...attachment,actor:member,activityId:act.id}));await checked(()=>care.setCareAttachmentArchived({...scope,actor:member,attachmentId:att.id,version:att.version,archived:true}));
 const r=await checked(()=>ops.createCareRiskCase({...risk,actor:member}));await checked(()=>ops.changeCareRiskCaseStatus({...scope,actor:member,riskCaseId:r.id,version:r.version,nextStatus:'ACKNOWLEDGED',resolutionEvidence:''}));
 const c=await checked(()=>ops.createCareCoveragePeriod({...coverage,actor:member}));await checked(()=>ops.changeCareCoverageStatus({...scope,actor:member,coverageId:c.id,version:c.version,nextStatus:'ACTIVE'}));
 const rev=await checked(()=>ops.createCareServiceReview({...review,actor:member}));await checked(()=>ops.updateCareServiceReview({...review,actor:member,reviewId:rev.id,version:rev.version}));await checked(()=>ops.changeCareServiceReviewStatus({...scope,actor:member,reviewId:rev.id,version:rev.version+1,nextStatus:'SUBMITTED'}));
 const approve={...scope,actor:owner,reviewId:rev.id,version:rev.version+2,nextStatus:'APPROVED' as const};await assert.rejects(ops.changeCareServiceReviewStatus({...approve,actor:member}),/Manager approval/);await checked(()=>ops.changeCareServiceReviewStatus(approve));
 const current=await prisma.careEngagement.findUniqueOrThrow({where:{id:project.id}});await checked(()=>care.changeCareEngagementStatus({...scope,actor:member,version:current.version,nextStatus:'PAUSED'}));
 // Multiple coverage submissions may not reserve overlapping backup periods.
 const later={...coverage,startAt:'2048-03-01',endAt:'2048-03-02',actor:owner};const race=await Promise.allSettled([ops.createCareCoveragePeriod(later),ops.createCareCoveragePeriod(later)]);assert.equal(race.filter(x=>x.status==='fulfilled').length,1);
 await prisma.careEngagementMember.updateMany({where:{engagementId:project.id,userId:member.id},data:{isActive:false}});await assert.rejects(care.addCarePlan({...plan,actor:member}),/no longer have permission/);await prisma.careEngagementMember.update({where:{id:membership.id},data:{isActive:true}});
 // Removed manager ACL cannot be overridden by a caller's captured operationsAdmin/role fields.
 const operator=await prisma.user.create({data:{name:'Isolated revoked ops',email:randomUUID()+'@example.invalid',role:'SALES',passwordHash:'isolated',passwordSalt:'isolated'}});const acl=await prisma.operationsAdminAcl.create({data:{email:operator.email}});await prisma.operationsAdminAcl.update({where:{id:acl.id},data:{isActive:false}});await assert.rejects(care.addCarePlan({...plan,actor:{...operator,role:'ADMIN'}}),/no longer have permission/);
 const otherStudent=await prisma.student.create({data:{name:'Isolated duplicate-track race'}});
 const draft={...create,actor:owner,studentId:otherStudent.id,scopeIds:['academic_management']};
 const drafts=await Promise.allSettled([care.createCareEngagement({...draft,programType:'PRE_U_ACADEMIC_CARE'}),care.createCareEngagement({...draft,programType:'PRE_U_FULL_COORDINATION'})]);assert.equal(drafts.filter(x=>x.status==='fulfilled').length,1);assert.equal(await prisma.careEngagement.count({where:{studentId:otherStudent.id}}),1);
 assert.equal(await prisma.packageTxn.count(),baseline.ledger);assert.equal(await prisma.miniappNotificationOutbox.count(),baseline.outbox);
 writeFileSync('/tmp/sgt-r455-fixture.json',JSON.stringify({engagementId:project.id,memberId:member.id,reviewId:rev.id,activityId:act.id}));
 console.log(JSON.stringify({passed:true,guardedMutations:calls.length,observerAndUnrelatedRoleDenied:true,managerOnlyRulesMatchUI:true,allMutationAuditRollback:true,activityConsentCurrent:true,concurrentCoverageOnce:true,concurrentSameTrackDraftOnce:true,currentMembershipAcl:true,noLedgerOrOutboxWrites:true}));
}
const watchdog=setTimeout(()=>{throw Error('Care staff UAT timed out');},30000);main().finally(()=>{clearTimeout(watchdog);return prisma.$disconnect();});
