import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';
import {getParentCareProgress,setCareParentVisibilitySection} from '../../lib/care-parent-visibility';
import {createParentPortalSession} from '../../lib/parent-portal';
async function main(){
 for(const key of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[key]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 const owner=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}});
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r456-fixture.json','utf8')),base='http://127.0.0.1:3149',url=base+'/api/miniapp/students/'+f.studentId+'/service-progress',headers={Authorization:'Bearer '+f.token};
  const res=await fetch(url,{headers});assert.equal(res.status,200);let text=await res.text();assert(!text.includes('\"UNKNOWN-SECRET\"'));assert(!text.includes('UNKNOWN-SECRET-TASK'));assert(!text.includes('CAREER-SECRET'));assert(!text.includes('GLOBAL-NEXT-SECRET'));assert(text.includes('ACADEMIC-PUBLIC'));assert.equal(JSON.parse(text).care.publishedActivityCount,14);
  const token=randomUUID();await prisma.authSession.create({data:{userId:owner.id,token,expiresAt:new Date(Date.now()+3600000)}});const staffUrl=base+'/admin/care/'+f.engagementId,cookie='ts_admin_session='+token;let html='';
  try{for(const language of ['EN','ZH','BILINGUAL'] as const){await prisma.user.update({where:{id:owner.id},data:{language}});html=await(await fetch(staffUrl,{headers:{Cookie:cookie}})).text();assert(html.includes(language==='EN'?'Unclassified history stays internal':'未分类的历史记录保留在内部'));}}finally{await prisma.user.update({where:{id:owner.id},data:{language:owner.language}});}
  const form=(html.match(/<form\b[^>]*>[\s\S]*?<\/form>/g)||[]).find(s=>s.includes('name="recordId"')&&s.includes(f.unknownId));assert(form);const fields=[...form.matchAll(/<input[^>]+name="([^"]+)"[^>]*value="([^"]*)"/g)].map(m=>[m[1],m[2].replaceAll('&quot;','"').replaceAll('&amp;','&')]);const action=form.match(/name="(\$ACTION_(?:REF|ID)_[^"]+)"/);assert(action);const data=new FormData();for(const [k,v]of fields)data.set(k,v);data.set(action[1],'');data.set('section','academic_progress');
  const saved=await fetch(staffUrl,{method:'POST',headers:{Cookie:cookie,Origin:base},body:data,redirect:'manual'});assert.equal(saved.status,303);assert.equal((await prisma.careActivity.findUniqueOrThrow({where:{id:f.unknownId}})).parentVisibilitySection,'academic_progress');text=await(await fetch(url,{headers})).text();assert(text.includes('UNKNOWN-SECRET'));
  await prisma.careUniversityProfile.update({where:{engagementId:f.engagementId},data:{studentConsentStatus:'WITHDRAWN'}});text=await(await fetch(url,{headers})).text();assert(!text.includes('ACADEMIC-PUBLIC'));assert(!text.includes('UNKNOWN-SECRET'));assert(!text.includes('REPORT-PUBLIC'));const hidden=JSON.parse(text);assert.equal(hidden.care.publishedActivityCount,0);assert.equal(hidden.care.publishedReportCount,0);assert.deepEqual(hidden.parentActions,[]);assert.deepEqual(hidden.care.visibleRisks,[]);assert.equal(hidden.care.latestPublishedUpdate,null);assert.equal(hidden.student.riskLabel,null);
  await prisma.careUniversityProfile.update({where:{engagementId:f.engagementId},data:{studentConsentStatus:'GRANTED'}});
  console.log(JSON.stringify({passed:true,explicitSectionFiltering:true,unknownHistoryHiddenUntilReviewed:true,trueCountsBeyondRecentLimit:true,consentWithdrawalAllSummaryPaths:true,threeLanguagesAndRealReviewForm:true}));return;
 }
 const student=await prisma.student.create({data:{name:'Isolated Care visibility '+randomUUID().slice(0,6),nextAction:'GLOBAL-NEXT-SECRET'}}),parent=await prisma.parentAccount.create({data:{name:'Isolated visibility parent'}});const link=await prisma.parentStudentLink.create({data:{parentId:parent.id,studentId:student.id,canViewReports:true}});
 const project=await prisma.careEngagement.create({data:{studentId:student.id,programType:'UNIVERSITY_GROWTH',status:'ACTIVE',scopeJson:[],createdByUserId:owner.id,universityProfile:{create:{studentConsentStatus:'GRANTED',parentVisibilityJson:{sectionIds:['academic_progress','formal_reports']}}}}});
 const activity=(title:string,section:string|null)=>prisma.careActivity.create({data:{studentId:student.id,engagementId:project.id,category:'GENERAL',occurredAt:new Date(),title,factEvidence:'Isolated facts',publicSummary:title,audience:'PARENT',publicationStatus:'PUBLISHED',parentVisibilitySection:section,createdByUserId:owner.id,updatedByUserId:owner.id}});
 for(let i=0;i<14;i++)await activity('ACADEMIC-PUBLIC '+i,'academic_progress');await activity('CAREER-SECRET','career_progress');const unknown=await activity('UNKNOWN-SECRET',null);
 await prisma.careTask.create({data:{studentId:student.id,engagementId:project.id,title:'Unknown task',assignedToUserId:owner.id,dueAt:new Date(),parentActionRequired:true,parentVisibleSummary:'UNKNOWN-SECRET-TASK',createdByUserId:owner.id}});
 const task=await prisma.careTask.create({data:{studentId:student.id,engagementId:project.id,title:'Reviewed task',assignedToUserId:owner.id,dueAt:new Date(),parentActionRequired:true,parentVisibleSummary:'ACADEMIC-PUBLIC-TASK',parentVisibilitySection:'academic_progress',createdByUserId:owner.id}});
 const risk=await prisma.careRiskCase.create({data:{studentId:student.id,engagementId:project.id,title:'Unknown risk',riskLevel:'LOW',facts:'Isolated facts',immediateAction:'Review',ownerUserId:owner.id,detectedAt:new Date(),responseDueAt:new Date(),parentVisible:true,publicSummary:'UNKNOWN-SECRET-RISK',createdByUserId:owner.id,updatedByUserId:owner.id}});
 await prisma.careReport.create({data:{studentId:student.id,engagementId:project.id,reportType:'MONTHLY',status:'PUBLISHED',periodLabel:'2048',periodStart:new Date('2048-01-01'),periodEnd:new Date('2048-01-31'),title:'REPORT-PUBLIC',overallSummary:'Summary',actionsCompleted:'Done',nextPlan:'Next',preparedByUserId:owner.id,publishedAt:new Date()}});
 let progress=await getParentCareProgress(student.id,parent.id,false);assert(progress);assert.equal(progress.activities.length,12);assert.equal(progress._count.activities,14);assert.equal(progress.tasks.length,1);assert.equal(progress.riskCases.length,0);assert.equal(progress._count.reports,1);
 const before=await prisma.careActivity.findUniqueOrThrow({where:{id:unknown.id}});const review={actorId:owner.id,engagementId:project.id,recordType:'ACTIVITY',recordId:unknown.id,version:before.version,section:'academic_progress'};
 let fail=true;prisma.$use(async(p,next)=>{if(fail&&p.model==='AuditLog'&&p.action==='create'&&p.args.data.action==='REVIEW_PARENT_VISIBILITY')throw Error('forced visibility audit failure');return next(p);});await assert.rejects(setCareParentVisibilitySection(review),/forced visibility audit/);assert.deepEqual(await prisma.careActivity.findUniqueOrThrow({where:{id:unknown.id}}),before);fail=false;
 const observer=await prisma.user.findFirstOrThrow({where:{name:'Policy OBSERVER'}});await assert.rejects(setCareParentVisibilitySection({...review,actorId:observer.id}),/Read-only/);await assert.rejects(setCareParentVisibilitySection({...review,section:'formal_reports'}),/valid summary section/);await assert.rejects(setCareParentVisibilitySection({...review,engagementId:'wrong-project'}),/No CareEngagement|not found/i);
 await setCareParentVisibilitySection({...review,recordType:'TASK',recordId:task.id,version:task.version,section:'career_progress'});progress=await getParentCareProgress(student.id,parent.id,false);assert.equal(progress!.tasks.length,0);
 await assert.rejects(setCareParentVisibilitySection({...review,recordType:'TASK',recordId:task.id,version:task.version,section:'academic_progress'}),/Record changed/);
 await setCareParentVisibilitySection({ ...review,recordType:'RISK',recordId:risk.id,version:risk.version,section:'academic_risks'});assert.equal((await getParentCareProgress(student.id,parent.id,false))!.riskCases.length,0);
 await prisma.careUniversityProfile.update({where:{engagementId:project.id},data:{parentVisibilityJson:{sectionIds:['academic_progress','academic_risks','formal_reports']}}});assert.equal((await getParentCareProgress(student.id,parent.id,false))!.riskCases.length,1);
 await prisma.careUniversityProfile.update({where:{engagementId:project.id},data:{studentConsentStatus:'WITHDRAWN'}});progress=await getParentCareProgress(student.id,parent.id,false);assert(progress);assert.deepEqual([progress._count.activities,progress._count.reports,progress.tasks.length,progress.riskCases.length],[0,0,0,0]);await prisma.careUniversityProfile.update({where:{engagementId:project.id},data:{studentConsentStatus:'GRANTED'}});
 await prisma.parentStudentLink.update({where:{id:link.id},data:{canViewReports:false}});assert.equal(await getParentCareProgress(student.id,parent.id,false),null);await prisma.parentStudentLink.update({where:{id:link.id},data:{canViewReports:true}});
 await prisma.careEngagement.update({where:{id:project.id},data:{programType:'PRE_U_ACADEMIC_CARE'}});progress=await getParentCareProgress(student.id,parent.id,true);assert.equal(progress!._count.activities,16);assert.equal(progress!.tasks.length,2);await prisma.careEngagement.update({where:{id:project.id},data:{programType:'UNIVERSITY_GROWTH'}});
 const session=await createParentPortalSession(parent.id);writeFileSync('/tmp/sgt-r456-fixture.json',JSON.stringify({studentId:student.id,engagementId:project.id,unknownId:unknown.id,token:session.token}));console.log(JSON.stringify({passed:true,explicitConsentAndSection:true,nullHistoryPreservedHidden:true,trueCountsAndRecentLists:true,reviewAuditRollbackScopeObserver:true,preUniversityPreserved:true}));
}
const watchdog=setTimeout(()=>{throw Error('Visibility UAT timed out');},30000);main().finally(()=>{clearTimeout(watchdog);return prisma.$disconnect();});
