import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';
import {communicationDeliveryEvidence} from '../../lib/communication-delivery-evidence';
async function main(){
 for(const key of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[key]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r459-fixture.json','utf8')),owner=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}}),token=randomUUID();await prisma.authSession.create({data:{userId:owner.id,token,expiresAt:new Date(Date.now()+3600000)}});
  const result=await fetch('http://127.0.0.1:3149/api/admin/communications?status=ALL&kind=FEEDBACK&limit=500',{headers:{Cookie:'ts_admin_session='+token}});assert.equal(result.status,200);const rows=(await result.json()).tasks;const row=rows.find((r:{id:string})=>r.id===f.taskId);assert(row);assert.equal(row.automaticNotification.status,'FAILED');assert.equal(row.automaticNotification.total,1);assert.equal(row.automaticNotification.scope,'CURRENT_FEEDBACK');assert(row.automaticNotification.note.includes('此家长'));assert(row.automaticNotification.note.includes('this parent'));
  console.log(JSON.stringify({passed:true,actualCommunicationListUsesRecipientAndCurrentRevision:true,bilingualEvidenceNote:true}));return;
 }
 const id=randomUUID(),student=await prisma.student.create({data:{name:'Isolated delivery scope '+id.slice(0,6)}}),otherStudent=await prisma.student.create({data:{name:'Other isolated recipient'}}),parent=await prisma.parentAccount.create({data:{name:'Exact isolated recipient'}}),other=await prisma.parentAccount.create({data:{name:'Other isolated parent'}}),teacher=await prisma.teacher.create({data:{name:'Isolated delivery teacher'}}),course=await prisma.course.findFirstOrThrow(),campus=await prisma.campus.findFirstOrThrow();
 const klass=await prisma.class.create({data:{teacherId:teacher.id,courseId:course.id,campusId:campus.id,capacity:1,oneOnOneStudentId:student.id}}),lesson=await prisma.session.create({data:{classId:klass.id,studentId:student.id,startAt:new Date('2049-02-01T02:00:00Z'),endAt:new Date('2049-02-01T03:00:00Z')}}),feedback=await prisma.sessionFeedback.create({data:{sessionId:lesson.id,teacherId:teacher.id,content:'Isolated reviewed feedback',reviewStatus:'PUBLISHED',publishedAt:new Date()}});
 const task=await prisma.parentCommunicationTask.create({data:{taskKey:'delivery-evidence:'+id,kind:'FEEDBACK',status:'READY_TO_SEND',priority:'HIGH',dueAt:new Date('2001-01-01'),studentId:student.id,parentId:parent.id,sessionId:lesson.id,feedbackId:feedback.id,title:'Isolated delivery counts',messageText:'Never sent'}});
 const queue=(parentId:string,studentId:string,targetId:string,status:string)=>prisma.miniappNotificationOutbox.create({data:{parentId,studentId,templateKey:'feedback_published',targetType:'SessionFeedback',targetId,eventType:'FEEDBACK_PUBLISHED',status,createdAt:new Date('2020-01-01')}});
 const old=await queue(parent.id,student.id,feedback.id,'FAILED');await queue(other.id,otherStudent.id,feedback.id,'SENT');
 // More than the old global sample limit, all belonging to other recipients.
 const recipients=Array.from({length:3001},()=>({id:randomUUID(),name:'Isolated sample-limit recipient'}));await prisma.parentAccount.createMany({data:recipients});await prisma.miniappNotificationOutbox.createMany({data:recipients.map(p=>({parentId:p.id,studentId:otherStudent.id,templateKey:'feedback_published',targetType:'SessionFeedback',targetId:feedback.id,eventType:'FEEDBACK_PUBLISHED',status:'SENT'}))});
 let result=(await communicationDeliveryEvidence([task])).get(task.id)!;assert.equal(result.status,'FAILED');assert.equal(result.total,1);
 const revision=feedback.id+':revision:'+randomUUID();await queue(parent.id,student.id,revision,'SENT');result=(await communicationDeliveryEvidence([task])).get(task.id)!;assert.equal(result.status,'NEEDS_REVIEW');
 await prisma.auditLog.create({data:{actorEmail:'isolated@example.test',module:'COMMUNICATION',action:'PUBLISH_FEEDBACK',entityType:'ParentCommunicationTask',entityId:task.id,meta:{feedbackId:feedback.id,notificationTargetId:revision}}});result=(await communicationDeliveryEvidence([task])).get(task.id)!;assert.equal(result.status,'SENT');assert.equal(result.total,1); // Old FAILED base cannot contaminate current publication.
 assert.equal((await communicationDeliveryEvidence([{...task,studentId:otherStudent.id}])).get(task.id)!.status,'NOT_QUEUED');
 await prisma.sessionFeedback.update({where:{id:feedback.id},data:{reviewStatus:'RETURNED'}});assert.equal((await communicationDeliveryEvidence([task])).get(task.id)!.status,'NEEDS_REVIEW');await prisma.sessionFeedback.update({where:{id:feedback.id},data:{reviewStatus:'PUBLISHED'}});
 assert.equal((await communicationDeliveryEvidence([{...task,parentId:null}])).get(task.id)!.status,'NEEDS_REVIEW');
 const courseScope={...task,id:randomUUID(),kind:'COURSE_REMINDER_PARENT',feedbackId:null};await prisma.miniappNotificationOutbox.create({data:{parentId:parent.id,studentId:student.id,templateKey:'course_reminder_24h',targetType:'Session',targetId:lesson.id+':24h',eventType:'COURSE_REMINDER',status:'PENDING',createdAt:new Date('2020-01-01')}});
 assert.equal((await communicationDeliveryEvidence([courseScope])).get(courseScope.id)!.status,'PENDING');assert.equal((await communicationDeliveryEvidence([{...courseScope,sessionId:null}])).get(courseScope.id)!.status,'NEEDS_REVIEW');
 const before={outbox:await prisma.miniappNotificationOutbox.count(),audits:await prisma.auditLog.count(),ledger:await prisma.packageTxn.count()};await communicationDeliveryEvidence([task,courseScope]);assert.deepEqual({outbox:await prisma.miniappNotificationOutbox.count(),audits:await prisma.auditLog.count(),ledger:await prisma.packageTxn.count()},before);
 await prisma.miniappNotificationOutbox.updateMany({where:{parentId:parent.id,targetId:revision},data:{status:'FAILED'}});writeFileSync('/tmp/sgt-r459-fixture.json',JSON.stringify({taskId:task.id}));assert.equal((await prisma.miniappNotificationOutbox.findUniqueOrThrow({where:{id:old.id}})).status,'FAILED');
 console.log(JSON.stringify({passed:true,completeCountsBeyond3000And14Days:true,exactParentAndStudent:true,currentAuditedRevisionOnly:true,unknownHistoryNeedsReview:true,returnedFeedbackNotSent:true,combinedLessonScopeNeedsReview:true,readOnlyEvidence:true}));
}
const watchdog=setTimeout(()=>{throw Error('Delivery evidence UAT timed out');},90000);main().finally(()=>{clearTimeout(watchdog);return prisma.$disconnect();});
