import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFileSync,writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';import {submitLeaveRequest,decideLeaveRequest,cancelLeaveRequest,getEmployeeLeaveBalances} from '../../lib/hr-leave';import {createStaffMiniappSession} from '../../lib/miniapp-staff';
async function main(){
 for(const key of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[key]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r466-fixture.json','utf8')),base='http://127.0.0.1:3149';
  const cookie=async(id:string)=>{const token=randomUUID();await prisma.authSession.create({data:{userId:id,token,expiresAt:new Date(Date.now()+3600000)}});return 'ts_admin_session='+token;};
  const mini=await createStaffMiniappSession(f.userId),headers={'Content-Type':'application/json',Authorization:'Bearer '+mini.token},path=base+'/api/miniapp/staff/hr/leave';
  const body={leaveType:'ANNUAL',startDate:'2052-02-12',endDate:'2052-02-12',reason:'Isolated HTTP leave'};const res=await fetch(path,{method:'POST',headers,body:JSON.stringify(body)});assert.equal(res.status,200,await res.text());const request=await prisma.hrLeaveRequest.findFirstOrThrow({where:{employeeId:f.employeeId,reason:body.reason}});assert.equal((await fetch(path,{method:'POST',headers,body:JSON.stringify(body)})).status,409);
  const hrCookie=await cookie(f.hrId),url=base+'/admin/hr/leave',html=await(await fetch(url,{headers:{Cookie:hrCookie}})).text(),form=(html.match(/<form\b[^>]*>[\s\S]*?<\/form>/g)||[]).find(s=>s.includes(`value="${request.id}"`));assert(form);
  const send=async(Cookie:string)=>{const data=new FormData();for(const m of form.matchAll(/<input[^>]+name="([^"]+)"[^>]*value="([^"]*)"/g))data.set(m[1],m[2].replaceAll('&quot;','"').replaceAll('&amp;','&'));const a=form.match(/name="(\$ACTION_(?:REF|ID)_[^"]+)"/);assert(a);data.set(a[1],'');data.set('decision','APPROVE');data.set('decisionNote','Isolated approval');return fetch(url,{method:'POST',headers:{Cookie,Origin:base},body:data,redirect:'manual'});};
  await send(await cookie(f.observerId));await send(await cookie(f.financeId));assert.equal((await prisma.hrLeaveRequest.findUniqueOrThrow({where:{id:request.id}})).status,'SUBMITTED');await send(hrCookie);assert.equal((await prisma.hrLeaveRequest.findUniqueOrThrow({where:{id:request.id}})).status,'APPROVED');
  const cancel=()=>fetch(path,{method:'POST',headers,body:JSON.stringify({action:'CANCEL',requestId:request.id,reason:'Isolated cancellation'})});assert.equal((await cancel()).status,200);assert.equal((await cancel()).status,409);assert.equal((await getEmployeeLeaveBalances(f.employeeId)).get('ANNUAL'),480);assert.equal(await prisma.hrLeaveLedgerEntry.count({where:{leaveRequestId:request.id,entryType:'RESTORED'}}),1);
  const webCookie=await cookie(f.userId),webUrl=base+'/staff/hr',web=await(await fetch(webUrl,{headers:{Cookie:webCookie}})).text(),selfForm=(web.match(/<form\b[^>]*>[\s\S]*?<\/form>/g)||[]).find(s=>s.includes('name="startDate"'));assert(selfForm);const d=new FormData();for(const m of selfForm.matchAll(/<input[^>]+name="([^"]+)"[^>]*value="([^"]*)"/g))d.set(m[1],m[2].replaceAll('&quot;','"').replaceAll('&amp;','&'));const a=selfForm.match(/name="(\$ACTION_(?:REF|ID)_[^"]+)"/);assert(a);d.set(a[1],'');for(const [k,v]of Object.entries({...body,startDate:'2052-02-13',endDate:'2052-02-13',portion:'FULL_DAY',reason:'Isolated Web leave'}))d.set(k,v);const saved=await fetch(webUrl,{method:'POST',headers:{Cookie:webCookie,Origin:base},body:d,redirect:'manual'});assert.equal(saved.status,303);assert.equal(await prisma.hrLeaveRequest.count({where:{employeeId:f.employeeId,reason:'Isolated Web leave',status:'SUBMITTED'}}),1);
  console.log(JSON.stringify({passed:true,webAndMiniSubmit:true,actualHrApproval:true,observerFinanceDenied:true,miniCancellationOnce:true,balanceRestored:true}));return;
 }
 const seed=JSON.parse(readFileSync('/tmp/sgt-r465-fixture.json','utf8')),hr=await prisma.user.findUniqueOrThrow({where:{id:seed.hrId}}),observer=await prisma.user.findUniqueOrThrow({where:{id:seed.observerId}}),finance=await prisma.user.findUniqueOrThrow({where:{id:seed.financeId}});
 const user=await prisma.user.create({data:{name:'Isolated leave employee',role:'CS',email:randomUUID()+'@example.invalid',passwordHash:'isolated',passwordSalt:'isolated'}}),entity=await prisma.hrLegalEntity.create({data:{name:'Isolated leave entity '+randomUUID()}}),employee=await prisma.employeeProfile.create({data:{userId:user.id,legalEntityId:entity.id,startDate:new Date('2051-01-01'),managerUserId:hr.id,createdByUserId:hr.id,updatedByUserId:hr.id}});
 await prisma.hrLeaveLedgerEntry.create({data:{employeeId:employee.id,leaveType:'ANNUAL',entryType:'OPENING',minutes:480,source:'ISOLATED',createdById:hr.id}});
 const input=(day:string)=>({employeeId:employee.id,leaveType:'ANNUAL' as const,startAt:new Date(day+'T00:00:00+08:00'),endAt:new Date(day+'T23:59:59.999+08:00'),reason:'Isolated service leave',actor:user});
 let fail='';prisma.$use(async(p,next)=>{if(p.model==='AuditLog'&&p.action==='create'&&p.args.data.action===fail)throw Error('forced leave audit failure');return next(p);});
 const snap=()=>Promise.all([prisma.hrLeaveRequest.findMany({where:{employeeId:employee.id},orderBy:{id:'asc'}}),prisma.hrLeaveLedgerEntry.findMany({where:{employeeId:employee.id},orderBy:{id:'asc'}})]);
 const baseline=await Promise.all([prisma.packageTxn.count(),prisma.miniappNotificationOutbox.count()]);let before=await snap();fail='LEAVE_SUBMITTED';await assert.rejects(submitLeaveRequest(input('2052-01-08')),/forced leave audit/);assert.deepEqual(await snap(),before);fail='';
 await assert.rejects(submitLeaveRequest({...input('2052-01-08'),actor:observer}),/Read-only/);await assert.rejects(submitLeaveRequest({...input('2052-01-08'),actor:finance}),/belong/);
 const policy=await prisma.hrLeavePolicy.create({data:{legalEntityId:entity.id,leaveType:'ANNUAL',requiresAttachment:true}});await assert.rejects(submitLeaveRequest(input('2052-01-08')),/attachment/);await prisma.hrLeavePolicy.update({where:{id:policy.id},data:{requiresAttachment:false}});
 const duplicates=await Promise.allSettled([submitLeaveRequest(input('2052-01-08')),submitLeaveRequest(input('2052-01-08'))]);assert.equal(duplicates.filter(r=>r.status==='fulfilled').length,1);
 const a=await prisma.hrLeaveRequest.findFirstOrThrow({where:{employeeId:employee.id}}),b=await submitLeaveRequest(input('2052-01-09'));
 const approve=(id:string,actor=hr)=>decideLeaveRequest({requestId:id,decision:'APPROVE',actor});
 before=await snap();for(const actor of [observer,finance,user])await assert.rejects(approve(a.id,actor));assert.deepEqual(await snap(),before);
 fail='LEAVE_APPROVED';await assert.rejects(approve(a.id),/forced leave audit/);assert.deepEqual(await snap(),before);fail='';
 const race=await Promise.allSettled([approve(a.id),approve(b.id)]);assert.equal(race.filter(r=>r.status==='fulfilled').length,1);assert.equal((await getEmployeeLeaveBalances(employee.id)).get('ANNUAL'),0);
 const approved=await prisma.hrLeaveRequest.findFirstOrThrow({where:{employeeId:employee.id,status:'APPROVED'}}),pending=await prisma.hrLeaveRequest.findFirstOrThrow({where:{employeeId:employee.id,status:'SUBMITTED'}});await assert.rejects(approve(pending.id),/balance/);
 const cancel=(actor=user)=>cancelLeaveRequest({requestId:approved.id,employeeUserId:user.id,actor,reason:'Isolated cancellation'});await assert.rejects(cancel({...finance,role:'ADMIN'}),/belong/);before=await snap();fail='LEAVE_CANCELLED';await assert.rejects(cancel(),/forced leave audit/);assert.deepEqual(await snap(),before);fail='';
 const cancels=await Promise.allSettled([cancel(),cancel()]);assert.equal(cancels.filter(r=>r.status==='fulfilled').length,1);assert.equal((await getEmployeeLeaveBalances(employee.id)).get('ANNUAL'),480);assert.equal(await prisma.hrLeaveLedgerEntry.count({where:{leaveRequestId:approved.id,entryType:'RESTORED'}}),1);
 await prisma.user.update({where:{id:hr.id},data:{isObserver:true}});await assert.rejects(approve(pending.id),/Read-only/);await prisma.user.update({where:{id:hr.id},data:{isObserver:false}});
 // Historical approved leave without exactly one evidenced deduction cannot invent a restoration.
 const historical=await prisma.hrLeaveRequest.create({data:{...{employeeId:employee.id,leaveType:'ANNUAL',startAt:new Date('2052-01-15'),endAt:new Date('2052-01-16'),durationMinutes:480,status:'APPROVED'},reason:'Isolated ambiguous history'}});before=await snap();await assert.rejects(cancelLeaveRequest({requestId:historical.id,employeeUserId:user.id,actor:user}),/ledger needs review/);assert.deepEqual(await snap(),before);
 assert.deepEqual(await Promise.all([prisma.packageTxn.count(),prisma.miniappNotificationOutbox.count()]),baseline);
 writeFileSync('/tmp/sgt-r466-fixture.json',JSON.stringify({employeeId:employee.id,userId:user.id,hrId:hr.id,observerId:observer.id,financeId:finance.id}));console.log(JSON.stringify({passed:true,overlapRaceOnce:true,independentApprovalsCannotOverspend:true,submitApproveCancelAuditRollback:true,currentActorAndExactOwnership:true,requiredAttachment:true,cancelRestoresOnce:true,unknownHistoryBlocked:true,tuitionAndOutboxUnchanged:true}));
}main().finally(()=>prisma.$disconnect());
