import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';
import {updateMonthlySchedulingItem,monthlySchedulingQueueLane,monthlySchedulingExceptionReason,getMonthlySchedulingCampaign} from '../../lib/monthly-scheduling';
import {createStaffMiniappSession} from '../../lib/miniapp-staff';
async function main(){
 for(const key of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[key]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 const actor=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}});
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r457-fixture.json','utf8')),base='http://127.0.0.1:3149',url=base+'/api/miniapp/staff/monthly-scheduling';
  const headers={Authorization:'Bearer '+f.token,'Content-Type':'application/json'};
  const response=await fetch(url,{method:'PATCH',headers,body:JSON.stringify({itemId:f.itemId,status:'PAUSED',expectedStatus:'PARENT_SELECTED',internalNote:'Isolated parent requested pause'})});assert.equal(response.status,200);
  const offers=await prisma.monthlySchedulingOffer.findMany({where:{itemId:f.itemId}});assert(offers.filter(o=>['AVAILABLE','HELD'].includes(o.status)).length===0);assert.equal(offers.filter(o=>o.status==='ACCEPTED').length,1);
  const listed=await fetch(url+'?month=2049-01&status=EXCEPTIONS',{headers});assert.equal(listed.status,200);assert((await listed.text()).includes(f.itemId));
  const staffToken=randomUUID();await prisma.authSession.create({data:{userId:actor.id,token:staffToken,expiresAt:new Date(Date.now()+3600000)}});
  try{for(const language of ['EN','ZH','BILINGUAL'] as const){await prisma.user.update({where:{id:actor.id},data:{language}});const page=await fetch(base+'/admin/monthly-scheduling?month=2049-01&lane=EXCEPTIONS',{headers:{Cookie:'ts_admin_session='+staffToken}});assert.equal(page.status,200);const html=await page.text();assert(html.includes(language==='EN'?'Pause/exclude releases temporary choices only':'暂停／排除仅释放临时候选时间'));assert(html.includes(language==='EN'?'Paused/excluded demand still has arrangements':'暂停／排除后仍有安排待核对'));}}finally{await prisma.user.update({where:{id:actor.id},data:{language:actor.language}});}
  console.log(JSON.stringify({passed:true,staffPatchAndExceptionList:true,threeLanguageWebGuidance:true,confirmedOfferRetained:true}));return;
 }
 const course=await prisma.course.findFirstOrThrow(),teacher=await prisma.teacher.create({data:{name:'Isolated closure '+randomUUID().slice(0,6)}}),campus=await prisma.campus.findFirstOrThrow();
 const campaign=await prisma.monthlySchedulingCampaign.upsert({where:{month:new Date('2049-01-01T00:00:00+08:00')},create:{month:new Date('2049-01-01T00:00:00+08:00'),status:'OPEN'},update:{}});
 async function make(){const student=await prisma.student.create({data:{name:'Isolated monthly closure '+randomUUID().slice(0,6)}});const item=await prisma.monthlySchedulingItem.create({data:{campaignId:campaign.id,studentId:student.id,courseId:course.id,token:randomUUID(),status:'PARENT_SELECTED',ownerUserId:actor.id,ownerName:'Original owner',parentNotes:'Original reply'}});let i=0;for(const status of ['AVAILABLE','HELD','ACCEPTED','COMPLETED','WITHDRAWN','EXPIRED'])await prisma.monthlySchedulingOffer.create({data:{itemId:item.id,teacherId:teacher.id,status,generation:i++,weekdayLabel:'MON',startMin:600,endMin:660,durationMin:60,holdExpiresAt:status==='HELD'?new Date(Date.now()+3600000):null,parentRank:status==='HELD'?1:null,acceptedAt:['ACCEPTED','COMPLETED'].includes(status)?new Date():null,sessionDatesJson:[{date:'2049-01-04',startAt:'2049-01-04T02:00:00Z',endAt:'2049-01-04T03:00:00Z'}]}});return item;}
 const first=await make(),klass=await prisma.class.create({data:{courseId:course.id,campusId:campus.id,teacherId:teacher.id,capacity:1,oneOnOneStudentId:first.studentId}}),lesson=await prisma.session.create({data:{classId:klass.id,studentId:first.studentId,startAt:new Date('2049-01-04T02:00:00Z'),endAt:new Date('2049-01-04T03:00:00Z')}});
 const counts=[await prisma.packageTxn.count(),await prisma.attendance.count(),await prisma.sessionFeedback.count(),await prisma.miniappNotificationOutbox.count()];
 const originalOffers=await prisma.monthlySchedulingOffer.findMany({where:{itemId:first.id},orderBy:{id:'asc'}});
 const input={itemId:first.id,status:'PAUSED' as const,expectedStatus:'PARENT_SELECTED' as const,expectedUpdatedAt:first.updatedAt.toISOString(),ownerUserId:actor.id,internalNote:'Parent requested pause; review confirmed lessons separately'};
 await assert.rejects(updateMonthlySchedulingItem({...input,internalNote:''}),/reason/);
 const observer=await prisma.user.findFirstOrThrow({where:{name:'Policy OBSERVER'}});await assert.rejects(updateMonthlySchedulingItem({...input,ownerUserId:observer.id}),/read-only/);
 let fail=true;prisma.$use(async(p,next)=>{if(fail&&p.model==='AuditLog'&&p.action==='create'&&p.args.data.entityId===first.id)throw Error('forced closure audit failure');return next(p);});await assert.rejects(updateMonthlySchedulingItem(input),/forced closure audit/);fail=false;assert.deepEqual(await prisma.monthlySchedulingOffer.findMany({where:{itemId:first.id},orderBy:{id:'asc'}}),originalOffers);assert.deepEqual(await prisma.monthlySchedulingItem.findUniqueOrThrow({where:{id:first.id}}),first);
 const race=await Promise.allSettled([updateMonthlySchedulingItem(input),updateMonthlySchedulingItem(input)]);assert.equal(race.filter(r=>r.status==='fulfilled').length,1);
 let saved=await prisma.monthlySchedulingItem.findUniqueOrThrow({where:{id:first.id}});assert.equal(saved.ownerName,first.ownerName);assert.equal(saved.parentNotes,first.parentNotes);
 const after=await prisma.monthlySchedulingOffer.findMany({where:{itemId:first.id},orderBy:{id:'asc'}});for(const before of originalOffers){const current=after.find(o=>o.id===before.id)!;if(['AVAILABLE','HELD'].includes(before.status)){assert.equal(current.status,'WITHDRAWN');assert.equal(current.holdExpiresAt,null);assert.equal(current.parentRank,before.parentRank);}else assert.deepEqual(current,before);}
 const audit=await prisma.auditLog.findFirstOrThrow({where:{entityId:first.id,action:'ITEM_STATUS_VERIFIED'}});assert.equal((audit.meta as {releasedOffers:unknown[]}).releasedOffers.length,2);
 const noted=await updateMonthlySchedulingItem({...input,expectedStatus:'PAUSED',expectedUpdatedAt:saved.updatedAt.toISOString()});assert.deepEqual(noted.pausedAt,saved.pausedAt);assert.deepEqual(await prisma.monthlySchedulingOffer.findMany({where:{itemId:first.id},orderBy:{id:'asc'}}),after);
 const campaignView=await getMonthlySchedulingCampaign('2049-01');const row=campaignView!.items.find(i=>i.id===first.id)!;assert.equal(monthlySchedulingQueueLane(row),'EXCEPTIONS');assert(monthlySchedulingExceptionReason(row,'EN')?.includes('retained'));assert(monthlySchedulingExceptionReason(row,'ZH')?.includes('保留'));
 const second=await make();await prisma.monthlySchedulingOffer.updateMany({where:{itemId:second.id,status:{in:['ACCEPTED','COMPLETED']}},data:{status:'WITHDRAWN'}});await updateMonthlySchedulingItem({...input,itemId:second.id,status:'EXCLUDED',expectedUpdatedAt:second.updatedAt.toISOString()});const closed=(await getMonthlySchedulingCampaign('2049-01'))!.items.find(i=>i.id===second.id)!;assert.equal(monthlySchedulingQueueLane(closed),'COMPLETED');assert.equal(closed.offers.length,0);
 assert.deepEqual(await prisma.session.findUniqueOrThrow({where:{id:lesson.id}}),lesson);assert.deepEqual([await prisma.packageTxn.count(),await prisma.attendance.count(),await prisma.sessionFeedback.count(),await prisma.miniappNotificationOutbox.count()],counts);
 const http=await make(),token=await createStaffMiniappSession(actor.id);writeFileSync('/tmp/sgt-r457-fixture.json',JSON.stringify({itemId:http.id,token:token.token}));
 console.log(JSON.stringify({passed:true,temporaryOffersReleased:true,confirmedAndHistoricalOffersRetained:true,formalLessonAndLedgerUntouched:true,atomicAuditRollback:true,concurrentClosureOnce:true,repeatTimestampPreserved:true,closedArrangementsRemainExceptions:true}));
}
const watchdog=setTimeout(()=>{throw Error('Monthly closure UAT timed out');},60000);main().finally(()=>{clearTimeout(watchdog);return prisma.$disconnect();});
