import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';
import {updateMonthlySchedulingItem,monthlySchedulingQueueLane,getMonthlySchedulingCampaign} from '../../lib/monthly-scheduling';
import {monthlyCompletionReviews} from '../../lib/monthly-scheduling-completion';
import {createStaffMiniappSession} from '../../lib/miniapp-staff';
async function main(){
 for(const k of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[k]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 const actor=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}}),course=await prisma.course.findFirstOrThrow(),campus=await prisma.campus.findFirstOrThrow(),teacher=await prisma.teacher.create({data:{name:'Monthly evidence UAT teacher'}});
 const student=await prisma.student.create({data:{name:'Monthly verification student '+randomUUID().slice(0,4)}}),other=await prisma.student.create({data:{name:'Other monthly student'}});
 const campaign=await prisma.monthlySchedulingCampaign.upsert({where:{month:new Date('2044-10-31T16:00:00Z')},create:{month:new Date('2044-10-31T16:00:00Z'),status:'OPEN'},update:{}});
 const klass=await prisma.class.create({data:{courseId:course.id,campusId:campus.id,teacherId:teacher.id,capacity:1,oneOnOneStudentId:student.id}});
 const sessions=[];for(const d of [1,8,15,22])sessions.push(await prisma.session.create({data:{classId:klass.id,studentId:student.id,startAt:new Date(`2044-11-${String(d).padStart(2,'0')}T02:00:00Z`),endAt:new Date(`2044-11-${String(d).padStart(2,'0')}T03:00:00Z`)}}));
 const row=await prisma.monthlySchedulingItem.create({data:{campaignId:campaign.id,studentId:student.id,courseId:course.id,token:randomUUID(),status:'MATCHED',intent:'KEEP',expectedMinutes:240,ownerUserId:actor.id,ownerName:'Original assigned owner',parentNotes:'Keep the four agreed dates'}});
 const offer=await prisma.monthlySchedulingOffer.create({data:{itemId:row.id,teacherId:teacher.id,status:'ACCEPTED',weekdayLabel:'FRI',startMin:600,endMin:660,durationMin:60,sessionDatesJson:sessions.map(s=>({date:s.startAt.toISOString().slice(0,10),startAt:s.startAt.toISOString(),endAt:s.endAt.toISOString()}))}});
 const input={itemId:row.id,status:'SCHEDULED' as const,expectedStatus:'MATCHED' as const,expectedUpdatedAt:row.updatedAt.toISOString(),ownerUserId:actor.id,sessionIds:sessions.map(s=>s.id),expectedSessionCount:4,completionReason:'Parent confirmed all four dates; timetable checked.'};
 const ledger=await prisma.packageTxn.count(),attendance=await prisma.attendance.count(),feedback=await prisma.sessionFeedback.count();
 await assert.rejects(updateMonthlySchedulingItem({...input,sessionIds:[sessions[0].id],expectedSessionCount:1}),/monthly minutes/);
 await assert.rejects(updateMonthlySchedulingItem({...input,expectedSessionCount:5}),/monthly total/);
 await assert.rejects(updateMonthlySchedulingItem({...input,expectedUpdatedAt:undefined}),/web workspace/);
 await assert.rejects(updateMonthlySchedulingItem({...input,completionReason:''}),/confirmation basis/);
 await assert.rejects(updateMonthlySchedulingItem({...input,sessionIds:[...input.sessionIds.slice(0,3),input.sessionIds[0]]}),/specific formal/);
 await prisma.attendance.create({data:{sessionId:sessions[0].id,studentId:student.id,status:'EXCUSED'}});
 await assert.rejects(updateMonthlySchedulingItem(input),/cancellation state/);await prisma.attendance.deleteMany({where:{sessionId:sessions[0].id}});
 await prisma.session.update({where:{id:sessions[0].id},data:{studentId:other.id}});await assert.rejects(updateMonthlySchedulingItem(input),/student or cancellation/);await prisma.session.update({where:{id:sessions[0].id},data:{studentId:student.id}});
 await prisma.session.update({where:{id:sessions[0].id},data:{startAt:new Date('2044-11-01T04:00:00Z'),endAt:new Date('2044-11-01T05:00:00Z')}});await assert.rejects(updateMonthlySchedulingItem(input),/confirmed option dates/);await prisma.session.update({where:{id:sessions[0].id},data:{startAt:sessions[0].startAt,endAt:sessions[0].endAt}});
 let failAudit=true;prisma.$use(async(params,next)=>{if(failAudit&&params.model==='AuditLog'&&params.action==='create'&&params.args.data.entityId===row.id)throw Error('forced monthly audit rollback');return next(params);});
 await assert.rejects(updateMonthlySchedulingItem(input),/forced monthly audit/);failAudit=false;
 assert.equal((await prisma.monthlySchedulingItem.findUniqueOrThrow({where:{id:row.id}})).status,'MATCHED');assert.equal((await prisma.monthlySchedulingOffer.findUniqueOrThrow({where:{id:offer.id}})).status,'ACCEPTED');
 const results=await Promise.allSettled([updateMonthlySchedulingItem(input),updateMonthlySchedulingItem(input)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
 let saved=await prisma.monthlySchedulingItem.findUniqueOrThrow({where:{id:row.id}});assert.equal(saved.ownerName,'Original assigned owner');assert.equal(saved.parentNotes,row.parentNotes);assert.equal(await prisma.auditLog.count({where:{entityId:row.id,action:'ITEM_STATUS_VERIFIED'}}),1);assert.equal((await prisma.monthlySchedulingOffer.findUniqueOrThrow({where:{id:offer.id}})).status,'COMPLETED');
 const noted=await updateMonthlySchedulingItem({itemId:row.id,status:'SCHEDULED',expectedStatus:'SCHEDULED',expectedUpdatedAt:saved.updatedAt.toISOString(),ownerUserId:actor.id,internalNote:'Follow-up note only'});assert.deepEqual(noted.scheduleEvidenceJson,saved.scheduleEvidenceJson);assert.deepEqual(noted.scheduledAt,saved.scheduledAt);
 assert.equal((await monthlyCompletionReviews([saved],campaign.month)).get(row.id)?.needsReview,false);
 await prisma.session.update({where:{id:sessions[0].id},data:{startAt:new Date('2044-11-01T04:00:00Z'),endAt:new Date('2044-11-01T05:00:00Z')}});
 assert.equal((await monthlyCompletionReviews([saved],campaign.month)).get(row.id)?.needsReview,true);await prisma.session.update({where:{id:sessions[0].id},data:{startAt:sessions[0].startAt,endAt:sessions[0].endAt}});
 assert.equal(monthlySchedulingQueueLane({status:'MATCHED'}),'READY_CONFIRM');assert.equal(monthlySchedulingQueueLane({status:'SCHEDULED',completionNeedsReview:true}),'EXCEPTIONS');
 const historical=await prisma.monthlySchedulingItem.create({data:{campaignId:campaign.id,studentId:other.id,courseId:course.id,token:randomUUID(),status:'SCHEDULED'}});
 assert.equal((await getMonthlySchedulingCampaign('2044-11'))?.items.find(i=>i.id===historical.id)?.completionNeedsReview,true);
 await assert.rejects(updateMonthlySchedulingItem({itemId:historical.id,status:'PAUSED',expectedStatus:'SCHEDULED',ownerUserId:actor.id}),/pause or exclusion reason/);
 assert.equal(await prisma.packageTxn.count(),ledger);assert.equal(await prisma.attendance.count(),attendance);assert.equal(await prisma.sessionFeedback.count(),feedback);
 const browserStudent=await prisma.student.create({data:{name:'Monthly browser completion student'}}),browserClass=await prisma.class.create({data:{teacherId:teacher.id,courseId:course.id,campusId:campus.id,capacity:1,oneOnOneStudentId:browserStudent.id}});
 const browserSession=await prisma.session.create({data:{classId:browserClass.id,studentId:browserStudent.id,startAt:new Date('2044-11-02T03:00:00Z'),endAt:new Date('2044-11-02T04:00:00Z')}});
 const browserItem=await prisma.monthlySchedulingItem.create({data:{campaignId:campaign.id,studentId:browserStudent.id,courseId:course.id,token:randomUUID(),status:'MATCHED',intent:'KEEP',expectedMinutes:60}});
 const token=await createStaffMiniappSession(actor.id);
 writeFileSync('/tmp/sgt-r435-fixture.json',JSON.stringify({itemId:row.id,historicalItemId:historical.id,browserItemId:browserItem.id,browserSessionId:browserSession.id,token:token.token,month:'2044-11',studentName:student.name}));
 console.log(JSON.stringify({passed:true,partialMissingDuplicateForeignCancelledMismatchRejected:true,atomicAuditRollback:true,concurrentCompletionOnce:true,ownerReplyPreserved:true,readOnlyStaleReview:true,historicalNeedsReview:true,financialTeachingDataUnchanged:true}));
}
main().finally(()=>prisma.$disconnect());
