import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {createStaffMiniappSession} from '../../lib/miniapp-staff';
import {createParentPortalSession} from '../../lib/parent-portal';
import {prisma} from '../../lib/prisma';
import {submitMonthlySchedulingFamilyKeep,submitMonthlySchedulingFamilyKeepByStaff,rankMonthlySchedulingOffers,rankMonthlySchedulingOffersByStaff,requestMonthlySchedulingChange} from '../../lib/monthly-scheduling';
async function main(){
 for(const k of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[k]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r439-fixture.json','utf8')),base='http://127.0.0.1:3149';
  const post=(staff:boolean,body:unknown)=>fetch(base+'/api/miniapp/'+(staff?'staff/':'')+'monthly-scheduling',{method:'POST',headers:{Authorization:`Bearer ${staff?f.token:f.parentToken}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
  const send={action:'KEEP_FAMILY',campaignId:f.campaignId};assert.equal((await post(false,send)).status,200);assert.equal((await post(false,send)).status,200);assert.equal(await prisma.parentPortalAudit.count({where:{parentId:f.parentId,action:'MONTHLY_FAMILY_KEEP'}}),2);
  assert.equal((await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:f.taskId}})).status,'WAIVED');
  await prisma.monthlySchedulingItem.update({where:{id:f.itemId},data:{status:'OFFERED',intent:'CHANGE'}});
  const offer=await prisma.monthlySchedulingOffer.create({data:{itemId:f.itemId,teacherId:f.teacherId,weekdayLabel:'MON',startMin:600,endMin:660,durationMin:60,sessionDatesJson:[{date:'2045-04-10',startAt:'2045-04-10T02:00:00Z',endAt:'2045-04-10T03:00:00Z'}]}});
  assert.equal((await post(true,{action:'PROXY_RANK_OFFERS',itemId:f.itemId,offerIds:[offer.id],responseChannel:'PHONE',parentConfirmationNote:'Isolated phone reply confirming first option.',parentConfirmedAt:new Date().toISOString()})).status,200);
  assert.equal(await prisma.auditLog.count({where:{entityId:f.itemId,action:'PROXY_PARENT_OFFER_RANKING'}}),1);
  const item=await prisma.monthlySchedulingItem.update({where:{id:f.itemId},data:{status:'MATCHED'}});const before=await prisma.monthlySchedulingOffer.findUniqueOrThrow({where:{id:offer.id}});
  assert.equal((await post(false,{action:'REQUEST_CHANGE',itemId:f.itemId,note:'Isolated new arrangement request',expectedUpdatedAt:item.updatedAt.toISOString()})).status,200);
  assert.equal(await prisma.parentPortalAudit.count({where:{targetId:f.itemId,action:'MONTHLY_CHANGE_REQUEST'}}),1);assert.deepEqual(await prisma.monthlySchedulingOffer.findUniqueOrThrow({where:{id:offer.id}}),before);
  console.log(JSON.stringify({passed:true,httpFamilyReplayIdempotent:true,httpStaffRankingAudit:true,httpChangeRequestRetainsOption:true}));return;
 }
 const actor=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}}),course=await prisma.course.create({data:{name:'Family reply UAT '+randomUUID().slice(0,4)}}),teacher=await prisma.teacher.create({data:{name:'Family selection isolated teacher'}});
 const campaign=await prisma.monthlySchedulingCampaign.upsert({where:{month:new Date('2045-03-31T16:00:00Z')},create:{month:new Date('2045-03-31T16:00:00Z'),status:'OPEN'},update:{status:'OPEN'}});
 const proxy={actorUserId:actor.id,actorEmail:actor.email,actorName:actor.name!,actorRole:actor.role,responseChannel:'WECHAT_GROUP' as const,parentConfirmationNote:'Isolated family confirmed these arrangements.',parentConfirmedAt:new Date().toISOString()};
 async function family(){const parent=await prisma.parentAccount.create({data:{name:'Family atomic UAT'}});const rows=[];for(let i=0;i<2;i++){const student=await prisma.student.create({data:{name:'Sibling UAT '+randomUUID().slice(0,4)}});await prisma.parentStudentLink.create({data:{parentId:parent.id,studentId:student.id}});rows.push(await prisma.monthlySchedulingItem.create({data:{campaignId:campaign.id,parentId:parent.id,studentId:student.id,courseId:course.id,token:randomUUID(),status:'SENT',carryForwardScheduleJson:[{weekdayCode:'MON',start:'10:00'}]}}));}const task=await prisma.parentCommunicationTask.create({data:{taskKey:`monthly-scheduling:${campaign.id}:${parent.id}`,parentId:parent.id,kind:'MONTHLY_SCHEDULING',status:'READY_TO_SEND',title:'Isolated reminder',messageText:'Isolated only'}});return {parent,rows,task};}
 const before={lessons:await prisma.session.count(),ledger:await prisma.packageTxn.count(),feedback:await prisma.sessionFeedback.count(),outbox:await prisma.miniappNotificationOutbox.count()};
 const f=await family();let failing='PROXY_FAMILY_KEEP_CURRENT';prisma.$use(async(p,next)=>{if(failing&&['AuditLog','ParentPortalAudit'].includes(p.model??'')&&p.action==='create'&&p.args.data.action===failing)throw Error('forced monthly audit failure');return next(p);});
 await assert.rejects(submitMonthlySchedulingFamilyKeepByStaff({...proxy,campaignId:campaign.id,seedItemId:f.rows[0].id}),/forced monthly audit/);
 for(const row of f.rows)assert.deepEqual(await prisma.monthlySchedulingItem.findUniqueOrThrow({where:{id:row.id}}),row);assert.deepEqual(await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:f.task.id}}),f.task);
 failing='';const success=await submitMonthlySchedulingFamilyKeepByStaff({...proxy,campaignId:campaign.id,seedItemId:f.rows[0].id});assert.equal(success.count,2);assert.equal((await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:f.task.id}})).status,'WAIVED');assert.equal(await prisma.auditLog.count({where:{entityId:success.batchId,action:'PROXY_FAMILY_KEEP_CURRENT'}}),1);
 const partial=await family();await prisma.parentStudentLink.update({where:{parentId_studentId:{parentId:partial.parent.id,studentId:partial.rows[1].studentId}},data:{canCreateRequests:false}});
 const part=await submitMonthlySchedulingFamilyKeep({campaignId:campaign.id,parentId:partial.parent.id});assert.equal(part.count,1);assert.equal((await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:partial.task.id}})).status,'READY_TO_SEND');assert.equal((await prisma.monthlySchedulingItem.findUniqueOrThrow({where:{id:partial.rows[1].id}})).status,'SENT');
 const race=await family();const races=await Promise.allSettled([submitMonthlySchedulingFamilyKeep({campaignId:campaign.id,parentId:race.parent.id}),submitMonthlySchedulingFamilyKeep({campaignId:campaign.id,parentId:race.parent.id})]);const completed=races.filter(r=>r.status==='fulfilled').map(r=>(r as PromiseFulfilledResult<{batchId:string}>).value);assert(completed.length>=1);assert.equal(new Set(completed.map(r=>r.batchId)).size,1);assert.equal(await prisma.parentPortalAudit.count({where:{parentId:race.parent.id,action:'MONTHLY_FAMILY_KEEP'}}),2);
 const pick=await family(),item=await prisma.monthlySchedulingItem.update({where:{id:pick.rows[0].id},data:{status:'OFFERED',intent:'CHANGE'}}),offer=await prisma.monthlySchedulingOffer.create({data:{itemId:item.id,teacherId:teacher.id,status:'AVAILABLE',generation:1,weekdayLabel:'MON',startMin:600,endMin:660,durationMin:60,sessionDatesJson:[{date:'2045-04-03',startAt:'2045-04-03T02:00:00Z',endAt:'2045-04-03T03:00:00Z'}]}}),old=await prisma.monthlySchedulingOffer.create({data:{itemId:item.id,teacherId:teacher.id,status:'WITHDRAWN',generation:0,parentRank:2,weekdayLabel:'MON',startMin:600,endMin:660,durationMin:60,sessionDatesJson:offer.sessionDatesJson!}});
 failing='PROXY_PARENT_OFFER_RANKING';await assert.rejects(rankMonthlySchedulingOffersByStaff({...proxy,itemId:item.id,offerIds:[offer.id]}),/forced monthly audit/);assert.deepEqual(await prisma.monthlySchedulingItem.findUniqueOrThrow({where:{id:item.id}}),item);assert.deepEqual(await prisma.monthlySchedulingOffer.findUniqueOrThrow({where:{id:offer.id}}),offer);
 failing='MONTHLY_OFFER_RANKING';await assert.rejects(rankMonthlySchedulingOffers({itemId:item.id,parentId:pick.parent.id,offerIds:[offer.id]}),/forced monthly audit/);assert.equal((await prisma.monthlySchedulingOffer.findUniqueOrThrow({where:{id:offer.id}})).status,'AVAILABLE');
 failing='';await rankMonthlySchedulingOffers({itemId:item.id,parentId:pick.parent.id,offerIds:[offer.id]});assert.deepEqual(await prisma.monthlySchedulingOffer.findUniqueOrThrow({where:{id:old.id}}),old);assert.equal(await prisma.parentPortalAudit.count({where:{targetId:item.id,action:'MONTHLY_OFFER_RANKING'}}),1);
 const matched=await prisma.monthlySchedulingItem.update({where:{id:item.id},data:{status:'MATCHED'}});await prisma.monthlySchedulingOffer.update({where:{id:offer.id},data:{status:'ACCEPTED'}});const accepted=await prisma.monthlySchedulingOffer.findUniqueOrThrow({where:{id:offer.id}});
 failing='MONTHLY_CHANGE_REQUEST';await assert.rejects(requestMonthlySchedulingChange({itemId:item.id,parentId:pick.parent.id,note:'Different day requested'}),/forced monthly audit/);assert.deepEqual(await prisma.monthlySchedulingItem.findUniqueOrThrow({where:{id:item.id}}),matched);
 failing='';await assert.rejects(requestMonthlySchedulingChange({itemId:item.id,parentId:pick.parent.id,note:'Different day requested',expectedUpdatedAt:'2000-01-01T00:00:00.000Z'}),/changed/);
 const changed=await requestMonthlySchedulingChange({itemId:item.id,parentId:pick.parent.id,note:'Different day requested',expectedUpdatedAt:matched.updatedAt.toISOString()});assert.equal(changed.status,'CHANGE_REQUESTED');assert.deepEqual(await prisma.monthlySchedulingOffer.findUniqueOrThrow({where:{id:offer.id}}),accepted);
 await prisma.monthlySchedulingCampaign.update({where:{id:campaign.id},data:{status:'CLOSED'}});await assert.rejects(submitMonthlySchedulingFamilyKeep({campaignId:campaign.id,parentId:f.parent.id}));await assert.rejects(requestMonthlySchedulingChange({itemId:f.rows[0].id,parentId:f.parent.id,note:'Closed campaign'}));await prisma.monthlySchedulingCampaign.update({where:{id:campaign.id},data:{status:'OPEN'}});
 assert.deepEqual({lessons:await prisma.session.count(),ledger:await prisma.packageTxn.count(),feedback:await prisma.sessionFeedback.count(),outbox:await prisma.miniappNotificationOutbox.count()},before);
 const httpFamily=await family(),staffToken=await createStaffMiniappSession(actor.id),parentToken=await createParentPortalSession(httpFamily.parent.id);
 writeFileSync('/tmp/sgt-r439-fixture.json',JSON.stringify({campaignId:campaign.id,itemId:httpFamily.rows[0].id,parentId:httpFamily.parent.id,taskId:httpFamily.task.id,teacherId:teacher.id,token:staffToken.token,parentToken:parentToken.token}));
 console.log(JSON.stringify({passed:true,familyAuditAndReminderRollback:true,partialFamilyKeepsReminder:true,parentScope:true,concurrentFamilyOnce:true,rankingAuditRollbackBothActors:true,oldRankHistoryRetained:true,changeRequestAuditedAndVersioned:true,acceptedArrangementRetained:true,closedCampaignRejected:true,noTeachingLedgerOrMessagesWritten:true}));
}
main().finally(()=>prisma.$disconnect());
