import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';
import {createSchoolApplicationDraft,prepareSchoolApplicationParentInfoLink,deleteSchoolApplicationParentInfoLink,markSchoolApplicationParentInfoViewed,markSchoolApplicationSignViewed,submitSchoolApplicationParentInfo,voidSchoolApplication} from '../../lib/school-application';
const info={parentName:'Isolated Parent',phone:'00000000',email:'isolated@example.invalid',studentSchool:'Isolated School',applicationNote:'New isolated note'};
async function main(){
 for(const key of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[key]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 const owner=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}});
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r451-fixture.json','utf8')),base='http://127.0.0.1:3149',url=base+'/school-application-info/'+f.token;
  const html=await(await fetch(url)).text(),action=html.match(/name="(\$ACTION_REF_[^"]+)"/),version=html.match(/name="expectedUpdatedAt" value="([^"]+)"/);assert(action);assert(version);
  const fields=[...html.matchAll(/<input[^>]+name="(\$ACTION_[^"]+)"[^>]*value="([^"]*)"/g)].map(m=>[m[1],m[2].replaceAll('&quot;','"').replaceAll('&amp;','&')]);
  const send=async()=>{const data=new FormData();for(const [key,value]of fields)data.set(key,value);data.set(action[1],'');data.set('token',f.token);data.set('expectedUpdatedAt',version[1]);for(const [key,value]of Object.entries(info))data.set(key,value);return fetch(url,{method:'POST',headers:{Origin:base},body:data,redirect:'manual'});};
  const r=await send();assert.equal(r.status,303);assert(!r.headers.get('location')?.includes('err='));const row=await prisma.schoolApplicationService.findUniqueOrThrow({where:{id:f.id}});assert.equal(row.status,'DRAFT');assert(row.parentInfoSubmittedAt);await send();assert.equal(await prisma.schoolApplicationEvent.count({where:{applicationId:f.id,eventType:'PARENT_INFO_SUBMITTED'}}),1);
  await deleteSchoolApplicationParentInfoLink({id:f.id,actorUserId:owner.id});const old=await(await fetch(url)).text();assert(old.includes('School Application Link Unavailable'));const blocked=await send();assert.equal(blocked.status,303);assert(blocked.headers.get('location')?.includes('err='));console.log(JSON.stringify({passed:true,publicFormSubmit:true,repeatOnce:true,revokedOldLinkDenied:true}));return;
 }
 const make=async()=>{const student=await prisma.student.create({data:{name:'Isolated parent info '+randomUUID().slice(0,6),note:'Existing staff note'}}),app=await prisma.schoolApplicationService.create({data:{studentId:student.id,status:'READY_TO_SIGN',applicationItemsJson:[],billTo:student.name,agreementDate:new Date(),parentInfoToken:randomUUID(),parentInfoExpiresAt:new Date(Date.now()+86400000),signToken:randomUUID(),signExpiresAt:new Date(Date.now()+86400000),contractSnapshotJson:{test:true}}});return {student,app};};
 const f=await make(),snap=async()=>({app:await prisma.schoolApplicationService.findUniqueOrThrow({where:{id:f.app.id},include:{events:true}}),student:await prisma.student.findUniqueOrThrow({where:{id:f.student.id}})});
 let failType='PARENT_INFO_VIEWED';prisma.$use(async(p,next)=>{if(p.model==='SchoolApplicationEvent'&&p.action==='create'&&p.args.data.eventType===failType)throw Error('forced parent info event failure');return next(p);});
 let before=await snap();await assert.rejects(markSchoolApplicationParentInfoViewed(f.app.id,f.app.parentInfoToken!),/forced parent info/);assert.deepEqual(await snap(),before);failType='';await Promise.all([markSchoolApplicationParentInfoViewed(f.app.id,f.app.parentInfoToken!),markSchoolApplicationParentInfoViewed(f.app.id,f.app.parentInfoToken!)]);assert.equal(await prisma.schoolApplicationEvent.count({where:{applicationId:f.app.id,eventType:'PARENT_INFO_VIEWED'}}),1);
 await markSchoolApplicationSignViewed(f.app.id,'wrong');assert.equal(await prisma.schoolApplicationEvent.count({where:{applicationId:f.app.id,eventType:'SIGN_VIEWED'}}),0);
 before=await snap();failType='PARENT_INFO_SUBMITTED';await assert.rejects(submitSchoolApplicationParentInfo({parentInfoToken:f.app.parentInfoToken!,parentInfo:info}),/forced parent info/);assert.deepEqual(await snap(),before);failType='';
 await assert.rejects(submitSchoolApplicationParentInfo({parentInfoToken:f.app.parentInfoToken!,parentInfo:info,expectedUpdatedAt:'stale'}),/refresh before submitting/);
 const submit=()=>submitSchoolApplicationParentInfo({parentInfoToken:f.app.parentInfoToken!,parentInfo:info});const races=await Promise.allSettled([submit(),submit()]);assert(races.some(x=>x.status==='fulfilled'));await submit();const submitted=await snap();assert.equal(submitted.app.status,'DRAFT');assert.equal(submitted.app.contractSnapshotJson,null);assert.deepEqual((submitted.app.events.find(e=>e.eventType==='PARENT_INFO_SUBMITTED')!.payloadJson as any).previousContractSnapshot,{test:true});assert(submitted.student.note?.includes('Existing staff note'));assert.equal(submitted.app.events.filter(e=>e.eventType==='PARENT_INFO_SUBMITTED').length,1);
 failType='PARENT_INFO_LINK_SENT';await assert.rejects(deleteSchoolApplicationParentInfoLink({id:f.app.id,actorUserId:owner.id}),/forced parent info/);assert.deepEqual(await snap(),submitted);failType='';await deleteSchoolApplicationParentInfoLink({id:f.app.id,actorUserId:owner.id});const revoked=await snap();assert.deepEqual(revoked.app.parentInfoViewedAt,submitted.app.parentInfoViewedAt);await assert.rejects(submit(),/unavailable/);await markSchoolApplicationParentInfoViewed(f.app.id,f.app.parentInfoToken!);assert.deepEqual(await snap(),revoked);
 // Pause after locating the public token; a concurrent revocation must prevent all writes.
 const stale=await make();let reached!:()=>void,release!:()=>void,paused=false;const gate=new Promise<void>(r=>release=r),read=new Promise<void>(r=>reached=r);prisma.$use(async(p,next)=>{const result=await next(p);if(!paused&&p.model==='SchoolApplicationService'&&p.action==='findUnique'&&p.args.where.parentInfoToken===stale.app.parentInfoToken){paused=true;reached();await gate;}return result;});const pending=submitSchoolApplicationParentInfo({parentInfoToken:stale.app.parentInfoToken!,parentInfo:info});await read;await deleteSchoolApplicationParentInfoLink({id:stale.app.id,actorUserId:owner.id});release();await assert.rejects(pending);assert.equal((await prisma.student.findUniqueOrThrow({where:{id:stale.student.id}})).note,'Existing staff note');
 const noteRace=await make();let noteReached!:()=>void,noteRelease!:()=>void,notePaused=false;const noteGate=new Promise<void>(r=>noteRelease=r),noteRead=new Promise<void>(r=>noteReached=r);
 prisma.$use(async(p,next)=>{const result=await next(p);if(!notePaused&&p.model==='SchoolApplicationService'&&p.action==='findUnique'&&p.args.where.id===noteRace.app.id&&p.args.include?.student){notePaused=true;noteReached();await noteGate;}return result;});
 const notePending=submitSchoolApplicationParentInfo({parentInfoToken:noteRace.app.parentInfoToken!,parentInfo:info});await noteRead;await prisma.student.update({where:{id:noteRace.student.id},data:{note:'Newer staff note'}});noteRelease();await assert.rejects(notePending);assert.equal((await prisma.student.findUniqueOrThrow({where:{id:noteRace.student.id}})).note,'Newer staff note');await submitSchoolApplicationParentInfo({parentInfoToken:noteRace.app.parentInfoToken!,parentInfo:info});assert((await prisma.student.findUniqueOrThrow({where:{id:noteRace.student.id}})).note?.includes('Newer staff note'));
 const closed=await make();await voidSchoolApplication({id:closed.app.id,actorUserId:owner.id});await assert.rejects(submitSchoolApplicationParentInfo({parentInfoToken:closed.app.parentInfoToken!,parentInfo:info}),/closed/);await markSchoolApplicationSignViewed(closed.app.id,closed.app.signToken!);assert.equal(await prisma.schoolApplicationEvent.count({where:{applicationId:closed.app.id,eventType:'SIGN_VIEWED'}}),0);
 const expired=await make();await prisma.schoolApplicationService.update({where:{id:expired.app.id},data:{parentInfoExpiresAt:new Date(0)}});await assert.rejects(submitSchoolApplicationParentInfo({parentInfoToken:expired.app.parentInfoToken!,parentInfo:info}),/expired/);
 const prepared=await make(),observer=await prisma.user.findFirstOrThrow({where:{name:'Policy OBSERVER'}});await assert.rejects(prepareSchoolApplicationParentInfoLink({id:prepared.app.id,actorUserId:observer.id}),/Read-only/);const refreshed=await prepareSchoolApplicationParentInfoLink({id:prepared.app.id,actorUserId:owner.id});assert.equal(refreshed.status,'DRAFT');assert.equal(refreshed.contractSnapshot,null);
 const empty=await prisma.student.create({data:{name:'Isolated atomic draft'}});failType='GENERATED';await assert.rejects(createSchoolApplicationDraft({studentId:empty.id,createdByUserId:owner.id}),/forced parent info/);assert.equal(await prisma.schoolApplicationService.count({where:{studentId:empty.id}}),0);assert.equal(await prisma.coursePackage.count({where:{studentId:empty.id}}),0);failType='';
 const http=await make();writeFileSync('/tmp/sgt-r451-fixture.json',JSON.stringify({id:http.app.id,studentId:http.student.id,token:http.app.parentInfoToken}));console.log(JSON.stringify({passed:true,viewAndSubmissionAuditRollback:true,viewsAndRepeatedSubmissionOnce:true,preservedNoteAndViewedHistory:true,staleVersionAndRevocationRaceDenied:true,expiredClosedAndWrongTokenDenied:true,preparationInvalidatesSnapshot:true,observerDenied:true,creationRollbackWithoutOrphanPackage:true}));
}
main().finally(()=>prisma.$disconnect());
