import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {prisma} from '../../lib/prisma';
import {saveTeacherFeedbackReviewed} from '../../lib/teacher-feedback-save';
import {ensureFeedbackCommunicationTasks,updateParentCommunicationTask} from '../../lib/parent-communication-center';
import {buildParentFeedbackText} from '../../lib/parent-feedback-format';
import {createStaffMiniappSession} from '../../lib/miniapp-staff';
const OPEN=['PENDING_REVIEW','READY_TO_SEND','CLAIMED','RETURNED','ATTENTION'];
async function main(){
 for(const key of ['DATABASE_URL','DIRECT_DATABASE_URL']){const u=new URL(process.env[key]||'');assert.equal(u.hostname,'127.0.0.1');assert.equal(u.port,'55439');assert.equal(u.pathname,'/sgt_workspace_completion_test');}
 const owner=await prisma.user.findUniqueOrThrow({where:{email:'zhaohongwei0880@gmail.com'}});
 const sections={lessonFocus:'Focus',currentFinding:'Finding',classPerformance:'Performance',nextPlan:'Next lesson',parentNote:'Review at home'};
 if(process.argv.includes('--http')){
  const f=JSON.parse(readFileSync('/tmp/sgt-r462-fixture.json','utf8')),token=randomUUID();await prisma.authSession.create({data:{userId:f.userId,token,expiresAt:new Date(Date.now()+3600000)}});const mini=await createStaffMiniappSession(f.userId),base='http://127.0.0.1:3149';
  for(const isMini of [false,true]){const res=await fetch(base+(isMini?'/api/miniapp/staff/schedule/':'/api/teacher/sessions/')+f.sessionId+'/feedback',{method:'POST',headers:{'Content-Type':'application/json',...(isMini?{Authorization:'Bearer '+mini.token}:{Cookie:'ts_admin_session='+token})},body:JSON.stringify({parentFeedbackSections:sections,homework:'Isolated homework',previousHomeworkDone:'yes'})});assert.equal(res.status,200,await res.text());const feedback=await prisma.sessionFeedback.findUniqueOrThrow({where:{id:f.feedbackId}});assert.equal(feedback.reviewStatus,'PENDING_REVIEW');assert.equal(await prisma.parentCommunicationTask.count({where:{kind:'FEEDBACK',feedbackId:f.feedbackId,status:{in:OPEN}}}),1);}
  await prisma.user.update({where:{id:f.userId},data:{isObserver:true}});const denied=await fetch(base+'/api/miniapp/staff/schedule/'+f.sessionId+'/feedback',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+mini.token},body:JSON.stringify({parentFeedbackSections:sections,homework:'Denied',previousHomeworkDone:'yes'})});assert.equal(denied.status,403);await prisma.user.update({where:{id:f.userId},data:{isObserver:false}});
  console.log(JSON.stringify({passed:true,webAndMiniSubmissionAtomic:true,oneCurrentReviewTask:true,observerRejected:true}));return;
 }
 const teacher=await prisma.teacher.create({data:{name:'Isolated feedback sync teacher'}}),student=await prisma.student.create({data:{name:'Isolated feedback sync student'}}),parent=await prisma.parentAccount.create({data:{name:'Isolated sync parent',wechatOpenId:'isolated-'+randomUUID()}});await prisma.parentStudentLink.create({data:{parentId:parent.id,studentId:student.id}});
 const user=await prisma.user.create({data:{name:'Isolated sync account',email:randomUUID()+'@example.invalid',role:'TEACHER',teacherId:teacher.id,passwordHash:owner.passwordHash,passwordSalt:owner.passwordSalt}}),course=await prisma.course.findFirstOrThrow(),campus=await prisma.campus.findFirstOrThrow();
 const klass=await prisma.class.create({data:{teacherId:teacher.id,courseId:course.id,campusId:campus.id,capacity:1,oneOnOneStudentId:student.id}}),session=await prisma.session.create({data:{classId:klass.id,studentId:student.id,startAt:new Date(Date.now()-7200000),endAt:new Date(Date.now()-3600000)}});
 let seq=0;const submit=(content:string)=>{const data={content,homework:'Practice',previousHomeworkDone:true,submittedAt:new Date(Date.now()+(++seq)*100),submittedByUserId:user.id};return saveTeacherFeedbackReviewed(session.id,teacher.id,{where:{sessionId_teacherId:{sessionId:session.id,teacherId:teacher.id}},create:{...data,sessionId:session.id,teacherId:teacher.id},update:data});};
 const long='Identical preview '.repeat(35),ledger=await prisma.packageTxn.count();let fail='';prisma.$use(async(p,next)=>{if(fail==='task'&&p.model==='ParentCommunicationTask'&&p.action==='create')throw Error('forced task sync failure');if(fail==='audit'&&p.model==='AuditLog'&&p.action==='create'&&p.args.data.action==='SUBMIT_TEACHER_FEEDBACK')throw Error('forced submit audit failure');return next(p);});
 fail='task';await assert.rejects(submit(long+'first'),/forced task sync/);assert.equal(await prisma.sessionFeedback.count({where:{sessionId:session.id}}),0);fail='';
 const initial=await submit(long+'first');let tasks=await ensureFeedbackCommunicationTasks(initial.id);assert.equal(tasks.length,1);const first=tasks[0];
 const publishedAt=new Date();await prisma.sessionFeedback.update({where:{id:initial.id},data:{reviewStatus:'PUBLISHED',publishedAt,parentContent:'Original reviewed parent content'}});const sent=await prisma.parentCommunicationTask.update({where:{id:first.id},data:{status:'COMPLETED',manualSentAt:new Date(),manualSentByName:'Original sender'}});
 for(const status of ['PENDING','FAILED','SENT','PROCESSING'])await prisma.miniappNotificationOutbox.create({data:{parentId:parent.id,studentId:student.id,templateKey:'feedback_published',eventType:'FEEDBACK_PUBLISHED',targetType:'SessionFeedback',targetId:initial.id+':revision:'+status,status,...(status==='SENT'?{sentAt:new Date()}:{} )}});
 const snapshot=async()=>({feedback:await prisma.sessionFeedback.findUniqueOrThrow({where:{id:initial.id}}),tasks:await prisma.parentCommunicationTask.findMany({where:{feedbackId:initial.id},orderBy:{id:'asc'}}),outbox:await prisma.miniappNotificationOutbox.findMany({where:{targetId:{startsWith:initial.id}},orderBy:{id:'asc'}}),audits:await prisma.auditLog.findMany({where:{entityId:initial.id},orderBy:{id:'asc'}})});
 for(const failure of ['task','audit']){fail=failure;const before=await snapshot();await assert.rejects(submit(long+'changed tail'),/forced/);assert.deepEqual(await snapshot(),before);}fail='';
 await submit(long+'changed tail');const changed=await snapshot();assert.equal(changed.feedback.reviewStatus,'PENDING_REVIEW');assert.deepEqual(changed.feedback.publishedAt,publishedAt);assert.equal(changed.feedback.parentContent,'Original reviewed parent content');assert.deepEqual(changed.tasks.find(t=>t.id===first.id),sent);assert.equal(changed.tasks.filter(t=>OPEN.includes(t.status)).length,1);assert.equal(changed.outbox.filter(o=>o.status==='SKIPPED').length,2);assert.equal(changed.outbox.filter(o=>o.status==='SENT').length,1);assert.equal(changed.outbox.filter(o=>o.status==='PROCESSING').length,1);
 const current=changed.tasks.find(t=>OPEN.includes(t.status))!;assert.notEqual(current.messageText,first.messageText);assert(current.messageText.includes(long+'changed tail'));assert.notEqual(current.contentFingerprint,first.contentFingerprint);
 await submit(long+'changed tail');tasks=await ensureFeedbackCommunicationTasks(initial.id);const newer=tasks[0];assert.notEqual(newer.id,current.id);assert.equal((await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:current.id}})).status,'SUPERSEDED');assert.equal(await prisma.parentCommunicationTask.count({where:{kind:'FEEDBACK',feedbackId:initial.id,status:{in:OPEN}}}),1);
 const act=(id:string,action:string,data:Record<string,unknown>={})=>updateParentCommunicationTask({id,action,actor:owner,data});await assert.rejects(act(current.id,'publish_feedback'),/replaced/);await assert.rejects(act(current.id,'retry_auto'),/replaced/);await assert.rejects(act(current.id,'manual_sent'),/closed/);
 await act(newer.id,'waive',{note:'No manual forwarding required'});const waived=await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:newer.id}});await submit(long+'changed tail');assert.deepEqual(await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:newer.id}}),waived);assert.equal(await prisma.parentCommunicationTask.count({where:{kind:'FEEDBACK',feedbackId:initial.id,status:{in:OPEN}}}),1);
 const unrelated=await prisma.parentCommunicationTask.create({data:{taskKey:'unrelated-kind:'+randomUUID(),kind:'COURSE_CHANGE',feedbackId:initial.id,studentId:student.id,title:'Historical different workflow',messageText:'Needs separate review',status:'ATTENTION'}});await ensureFeedbackCommunicationTasks(initial.id);assert.deepEqual(await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:unrelated.id}}),unrelated);
 const [review]=await ensureFeedbackCommunicationTasks(initial.id);await act(review.id,'publish_feedback',{parentContent:buildParentFeedbackText(sections)});assert.equal(await prisma.parentCommunicationTask.count({where:{kind:'FEEDBACK',feedbackId:initial.id,status:{in:OPEN}}}),1);assert.equal((await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:current.id}})).status,'SUPERSEDED');await act(review.id,'manual_sent');assert((await prisma.sessionFeedback.findUniqueOrThrow({where:{id:initial.id}})).forwardedAt);await act(review.id,'return_feedback',{note:'Correct examples'});assert.equal((await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:current.id}})).status,'SUPERSEDED');
 assert.deepEqual(await prisma.parentCommunicationTask.findUniqueOrThrow({where:{id:unrelated.id}}),unrelated);
 const beforeDenied=await snapshot();await prisma.user.update({where:{id:user.id},data:{isObserver:true}});await assert.rejects(submit('Denied'),/account/);assert.deepEqual(await snapshot(),beforeDenied);await prisma.user.update({where:{id:user.id},data:{isObserver:false,teacherId:null}});await assert.rejects(submit('Denied'),/account/);await prisma.user.update({where:{id:user.id},data:{teacherId:teacher.id}});
 const races=await Promise.allSettled([submit('Concurrent A'),submit('Concurrent B')]);assert(races.some(r=>r.status==='fulfilled'));assert.equal(await prisma.parentCommunicationTask.count({where:{kind:'FEEDBACK',feedbackId:initial.id,status:{in:OPEN}}}),1);assert.equal(await prisma.packageTxn.count(),ledger);assert.deepEqual(await prisma.session.findUniqueOrThrow({where:{id:session.id}}),session);

 writeFileSync('/tmp/sgt-r462-fixture.json',JSON.stringify({userId:user.id,sessionId:session.id,feedbackId:initial.id}));console.log(JSON.stringify({passed:true,taskSyncAndAuditRollback:true,longTailAndSameTextResubmissionReview:true,sentAndWaivedHistoryPreserved:true,oneCurrentReviewTask:true,oldReviewAndRetryDenied:true,pendingOldOutboxInvalidated:true,sentProcessingNotRevoked:true,freshTeacherIdentity:true,concurrentSubmission:true,noLedgerOrLessonWrites:true}));
}
const timer=setTimeout(()=>{throw Error('Teacher sync UAT timeout');},60000);main().finally(()=>{clearTimeout(timer);return prisma.$disconnect();});
