-- NOTE:
-- This migration was created during an early deployment and ended up being replaced by a later migration
-- (20260209093000_create_one_on_one_group_and_link_class) that creates the OneOnOneGroup table and links Class.
--
-- We intentionally keep this migration as a no-op to preserve migration history while avoiding dependency ordering
-- issues on fresh databases.
